---
title: "All sites analyses for a defendable thesis"
author: "Josie Lesage"
date: "12/7/2019"
output: html_document
---

# Setup and data import
```{r setup, include=FALSE}
## community analysis
library(codyn)
library(MASS)
library(lme4)
library(nlme)
library(vegan)


## misc/both/other
library(oz)
library(plotrix)
library(gridExtra)
library(stringr)
library(tidyverse)


# to rip legends out of figures
g_legend <- function(a.gplot){ 
    tmp <- ggplot_gtable(ggplot_build(a.gplot)) 
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box") 
    legend <- tmp$grobs[[leg]] 
    legend
} 
```

```{r com data import, echo=FALSE}
rel_all <- read.csv("Analysis/ComData/AllData_Relative.csv")
```

```{r prism data import and prep, echo = FALSE}
weather <- read.csv("Analysis/ClimData/PRISM_data.csv") %>%
  select(-X)

wtryr_weather <- read.csv("Analysis/ClimData/PRISM_wtryr_data.csv") %>%
  select(-X)

```

# Changes in guild-level cover over time

```{r converting species level cover to guild level cover}
gcov_all <- rel_all %>%
  filter(guild != "NANANA",
         !is.na(cover)) %>%
  group_by(site, year, plot, guild) %>%
  summarise(cover = sum(cover)) %>% ungroup() %>%
  group_by(site, year, plot) %>%
  mutate(sumcov = sum(cover),
         relcov = cover/sumcov) %>% select(site, plot, year, relcov, guild) %>%
  spread(guild, relcov) %>%
  replace(is.na(.), 0) %>%
  mutate(Nat = (NAF+NAG+NAGr+NPF+NPG+NPGr+NPS+NPT),
         Exo = (EAF+EAG+EPF+EPG),
         Ann = (NAF+NAG+NAGr+EAF+EAG),
         Per = (NPF+NPG+NPGr+NPS+NPT+EPF+EPG),
         NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT),
         NatGr = (NAG+NAGr+NPG+NPGr),
         NatForb = (NAF+NPF+NPS+NPT),
         ExoGr = (EAG+EPG),
         ExoForb = (EAF+EPF),
         NatAnGr = (NAG + NAGr),
         NatPerGr = (NPG + NPGr),
         NatAnFo = (NAF),
         NatPerFo = (NPF + NPS + NPT),
         ExoAnGr = (EAG),
         ExoPerGr = (EPG),
         ExoAnFo = (EAF),
         ExoPerFo = (EPF),
         Grasses = (NPG+NPGr+NAG+NAGr+EAG+EPG),
         Forbs = (NAF+NPF+NPS+NPT+EAF+EPF),
         All = (NAF+NAG+NAGr+NPF+NPG+NPGr+NPS+NPT+EAF+EAG+EPF+EPG)) %>%
  ungroup() %>% 
  gather('All', 'Nat', 'Exo', 'NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', 'Forbs', 'Grasses', 'NatGr', 'NatForb', 'ExoGr', 'ExoForb', 'NatAnGr', 'NatPerGr', 'NatAnFo', 'NatPerFo', 'ExoAnGr', 'ExoPerGr', 'ExoAnFo', 'ExoPerFo', "Ann", "Per", key = "guild", value = "relcov") %>%
  group_by(site, year, guild, plot) %>%
  summarise(relcov2 = relcov, 
            meancov = mean(relcov),
            secov = (std.error(relcov2)))

# write.csv(gcov_all, "Analysis/JMP Exports/GuildCover.csv")

gcov_all <- left_join(gcov_all, wtryr_weather, by = c("year", "site")) %>%
  mutate(meancov2 = meancov,
         meancov = meancov2*100)

gcov_all_means <- gcov_all %>%
  group_by(site, guild, year) %>%
  summarise(serelcov = (std.error(meancov)),
            meanrelcov = mean(meancov),
            precip = mean(precip),
            tmean = mean(tmean),
            tmax = mean(tmax),
            tmin = mean(tmin)) %>%
  filter(guild == "Nat" | guild == "Exo")
#   filter(guild == "NatForb" | guild == "NatGr" | guild == "ExoForb" | guild == "ExoGr")
#  filter(guild == "Nat" | guild == "NatAnGr" | guild == "NatPerGr" | guild == "NatAnFo" | guild == "NatPerFo")
#  filter(guild == "Exo" | guild == "ExoAnGr" | guild == "ExoPerGr" | guild == "ExoAnFo" | guild == "ExoPerFo")

gcov_all_means <- gcov_all_means %>%
  mutate(guild = recode(guild,
                        "ExoForb" = "Non-native forbs",
                        "NatForb" = "Native forbs",
                        "ExoGr" = "Non-native grasses",
                        "NatGr" = "Native grasses",
                        "Nat" = "Native",
                        "Exo" = "Non-native"))

siglevels <- read.csv("Analysis/2020 Analysis/siglevels.csv")

gcov_all_means <- left_join(gcov_all_means, siglevels)

ggplot(gcov_all_means, aes(x = year, y = meanrelcov, color = guild)) +
  geom_line() +
  scale_linetype_manual(values=c("dotted", "solid")) +
  geom_errorbar(aes(ymin = (meanrelcov - serelcov), ymax = (meanrelcov + serelcov))) +
  labs(title = "All sites - Relative cover over time",
       x = "Year",
       y = "% Cover (relative)") +
  theme_bw() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = -90, vjust = 0.5)) +
  scale_y_continuous(limits = c(0,NA)) + 
  expand_limits(y = 0)+
  facet_grid(vars(guild), vars(site), scales = "free")

```

```{r NATIVE FORB COVER MODELS}
gcov_all_natf <- gcov_all %>%
  filter(guild == "NatForb") %>%
  mutate(year2 = year,
         # we rescale the year to improve the model and prevent eigenvalue warnings
         year = abs(year2-1983))

gcov_all_natf$year <- as.numeric(gcov_all_natf$year)

# Angelo
summary(glm(meancov ~ year ,  
              data = gcov_all_natf[gcov_all_natf$site == "Angelo",]))

# Carrizo - has a problem, inconsistent plots -- ignore data?
summary(glm(meancov ~ year, 
              data = gcov_all_natf[gcov_all_natf$site == "Carrizo",]))

# Elkhorn
summary(glm(meancov ~ year,
              data = gcov_all_natf[gcov_all_natf$site == "Elkhorn",]))

# Jasper
summary(glm(meancov ~ year, 
              data = gcov_all_natf[gcov_all_natf$site == "Jasper",]))

# McL Ann
summary(glm(meancov ~ year, 
              data = gcov_all_natf[gcov_all_natf$site == "McL Ann",]))

# McL Serp
summary(glm(meancov ~ year, 
              data = gcov_all_natf[gcov_all_natf$site == "McL Serp",]))

# Swanton
summary(glm(meancov ~ year, 
              data = gcov_all_natf[gcov_all_natf$site == "Swanton",]))

# UCSC
summary(glm(meancov ~ year,
            data = gcov_all_natf[gcov_all_natf$site == "UCSC",]))

```

```{r NATIVE Grass COVER MODELS}
gcov_all_natgr <- gcov_all %>%
  filter(guild == "NatGr") %>%
  mutate(year2 = year,
         # we rescale the year to improve the model and prevent eigenvalue warnings
         year = abs(year2-1983))

gcov_all_natgr$year <- as.numeric(gcov_all_natgr$year)

# Angelo
summary(glm(meancov ~ year ,  
              data = gcov_all_natgr[gcov_all_natgr$site == "Angelo",]))

# Carrizo - has a problem, inconsistent plots -- ignore data?
summary(glm(meancov ~ year, 
              data = gcov_all_natgr[gcov_all_natgr$site == "Carrizo",]))

# Elkhorn
summary(glm(meancov ~ year,
              data = gcov_all_natgr[gcov_all_natgr$site == "Elkhorn",]))

# Jasper
summary(glm(meancov ~ year, 
              data = gcov_all_natgr[gcov_all_natgr$site == "Jasper",]))

# McL Ann
summary(glm(meancov ~ year, 
              data = gcov_all_natgr[gcov_all_natgr$site == "McL Ann",]))

# McL Serp
summary(glm(meancov ~ year, 
              data = gcov_all_natgr[gcov_all_natgr$site == "McL Serp",]))

# Swanton
summary(glm(meancov ~ year, 
              data = gcov_all_natgr[gcov_all_natgr$site == "Swanton",]))

# UCSC
summary(glm(meancov ~ year,
            data = gcov_all_natgr[gcov_all_natgr$site == "UCSC",]))

```

```{r EXOTIC FORB MODELS}
gcov_all_exof <- gcov_all %>%
  filter(guild == "ExoForb") %>%
  mutate(year2 = year,
         # we rescale the year to improve the model and prevent eigenvalue warnings
         year = abs(year2-1983))

gcov_all_exof$year <- as.numeric(gcov_all_exof$year)

# Angelo
summary(glm(meancov ~ year,  
              data = gcov_all_exof[gcov_all_exof$site == "Angelo",]))

# Carrizo - has a problem, inconsistent plots -- ignore data?
summary(glm(meancov ~ year, 
              data = gcov_all_exof[gcov_all_exof$site == "Carrizo",]))

# Elkhorn
summary(glm(meancov ~ year,
              data = gcov_all_exof[gcov_all_exof$site == "Elkhorn",]))

# Jasper
summary(glm(meancov ~ year, 
              data = gcov_all_exof[gcov_all_exof$site == "Jasper",]))

# McL Ann
summary(glm(meancov ~ year, 
              data = gcov_all_exof[gcov_all_exof$site == "McL Ann",]))

# McL Serp
summary(glm(meancov ~ year, 
              data = gcov_all_exof[gcov_all_exof$site == "McL Serp",]))

# Swanton
summary(glm(meancov ~ year, 
            data = gcov_all_exof[gcov_all_exof$site == "Swanton",]))

# UCSC
summary(glm(meancov ~ year,
            data = gcov_all_exof[gcov_all_exof$site == "UCSC",]))

```


```{r EXOTIC GRASS MODELS}
gcov_all_exogr <- gcov_all %>%
  filter(guild == "Exo") %>%
  mutate(year2 = year,
         # we rescale the year to improve the model and prevent eigenvalue warnings
         year = abs(year2-1983))

gcov_all_exogr$year <- as.numeric(gcov_all_exogr$year)

# Angelo
summary(glm(meancov ~ year,  
              data = gcov_all_exogr[gcov_all_exogr$site == "Angelo",]))

# Carrizo - has a problem, inconsistent plots -- ignore data?
summary(glm(meancov ~ year, 
              data = gcov_all_exogr[gcov_all_exogr$site == "Carrizo",]))

# Elkhorn
summary(glm(meancov ~ year,
              data = gcov_all_exogr[gcov_all_exogr$site == "Elkhorn",]))

# Jasper
summary(glm(meancov ~ year, 
              data = gcov_all_exogr[gcov_all_exogr$site == "Jasper",]))

# McL Ann
summary(glm(meancov ~ year, 
              data = gcov_all_exogr[gcov_all_exogr$site == "McL Ann",]))

# McL Serp
summary(glm(meancov ~ year, 
              data = gcov_all_exogr[gcov_all_exogr$site == "McL Serp",]))

# Swanton
summary(glm(meancov ~ year, 
              data = gcov_all_exogr[gcov_all_exogr$site == "Swanton",]))

# UCSC
summary(glm(meancov ~ year,
            data = gcov_all_exogr[gcov_all_exogr$site == "UCSC",]))

```


# Species richness over time

```{r data prep and summary graphs, echo = FALSE}
grich_all <- rel_all %>%
  group_by(site, year, plot, guild) %>%
  summarise(rich = n_distinct(species.name)) %>%
  spread(guild, rich) %>%
  replace(is.na(.), 0) %>%
  mutate(Nat = (NAF+NAG+NAGr+NPF+NPG+NPGr+NPS+NPT),
         Exo = (EAF+EAG+EPF+EPG),
         NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT),
         NatGr = (NAG+NAGr+NPG+NPGr),
         NatForb = (NAF+NPF+NPS+NPT),
         ExoGr = (EAG+EPG),
         ExoForb = (EAF+EPF),
         Grasses = (NPG+NPGr+NAG+NAGr+EAG+EPG),
         Forbs = (NAF+NPF+NPS+NPT+EAF+EPF),
         All = Nat + Exo) %>%
  ungroup() %>% 
  gather('Nat', 'Exo', 'NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', 'Forbs', 'Grasses', "All", key = "guild", value = "rich") %>%
  group_by(site, year, plot, guild) %>%
  summarise(meanrich = mean(rich))

# write.csv(grich_all, "Analysis/JMP Exports/GuildRichness.csv")

grich_all_weather <- left_join(grich_all, wtryr_weather, by = c("year", "site")) 

grich_all_means <- grich_all_weather %>%
  group_by(site, guild, year) %>%
  summarise(serich = std.error(meanrich),
            meanrich = mean(meanrich),
            precip = mean(precip),
            tmean = mean(tmean),
            tmax = mean(tmax),
            tmin = mean(tmin)) %>%
  filter(guild == "All" | guild == "Exo" | guild == "Nat")

grich_all_means <- grich_all_means %>%
  mutate(guild = recode(guild,
                        "Exo" = "Exotic",
                        "Nat" = "Native",
                        "All" = "All Species"))
  
ggplot(grich_all_means, aes(x = year, y = meanrich, color = guild)) +
  geom_line() +
  geom_errorbar(aes(ymin = (meanrich - serich), ymax = (meanrich + serich))) +
  labs(title = "All sites - Richness over time",
       x = "Year",
       y = "Richness (# spp.)") +
  facet_wrap(~site, scales = "free", ncol = 4) +
  theme_bw() +
  scale_y_continuous(limits = c(0,NA)) + 
  expand_limits(y = 0) +
  geom_smooth(method='lm')

```

```{r TOTAL RICHNESS MODELS}
grich_all_totalrich <- grich_all %>%
  filter(guild == "All") %>%
  mutate(year2 = year,
         # we rescale the year to improve the model and prevent eigenvalue warnings
         year = abs(year2-1983))

grich_all_totalrich$year <- as.numeric(grich_all_totalrich$year)

# Angelo
summary(glmer(meanrich ~ year + (1|plot), family = "poisson", 
            data = grich_all_totalrich[grich_all_totalrich$site == "Angelo",]))

# Carrizo -- LOOKS WEIRD?
summary(glmer(meanrich ~ year + (1|plot), family = "poisson",  
              data = grich_all_totalrich[grich_all_totalrich$site == "Carrizo",]))

# Elkhorn
summary(glmer(meanrich ~ year + (1|plot), family = "poisson", 
              data = grich_all_totalrich[grich_all_totalrich$site == "Elkhorn",]))

# Jasper
summary(glmer(meanrich ~ year + (1|plot), family = "poisson",  
              data = grich_all_totalrich[grich_all_totalrich$site == "Jasper",]))

# McL Ann
summary(glmer(meanrich ~ year + (1|plot), family = "poisson",  
              data = grich_all_totalrich[grich_all_totalrich$site == "McL Ann",]))

# McL Serp
summary(glmer(meanrich ~ year + (1|plot), family = "poisson",  
              data = grich_all_totalrich[grich_all_totalrich$site == "McL Serp",]))

# Swanton
summary(glmer(meanrich ~ year + (1|plot), family = "poisson",  
              data = grich_all_totalrich[grich_all_totalrich$site == "Swanton",]))

# UCSC
summary(glmer(meanrich ~ year + (1|plot), family = "poisson",  
            data = grich_all_totalrich[grich_all_totalrich$site == "UCSC",]))

```

```{r NATIVE RICHNESS MODELS}
grich_all_natrich <- grich_all %>%
  filter(guild == "Nat") %>%
  mutate(year2 = year,
         # we rescale the year to improve the model and prevent eigenvalue warnings
         year = abs(year2-1983))

grich_all_natrich$year <- as.numeric(grich_all_natrich$year)

# Angelo
summary(glmer(meanrich ~ year + (1|plot), family = "poisson",  
              data = grich_all_natrich[grich_all_natrich$site == "Angelo",]))

# Carrizo - has a problem, inconsistent plots -- ignore data?
summary(glmer(meanrich ~ year + (1|plot), family = "poisson",  
              data = grich_all_natrich[grich_all_natrich$site == "Carrizo",]))

# Elkhorn
summary(glmer(meanrich ~ year + (1|plot), family = "poisson",  
              data = grich_all_natrich[grich_all_natrich$site == "Elkhorn",]))

# Jasper
summary(glmer(meanrich ~ year + (1|plot), family = "poisson",  
              data = grich_all_natrich[grich_all_natrich$site == "Jasper",]))

# McL Ann
summary(glmer(meanrich ~ year + (1|plot), family = "poisson",  
              data = grich_all_natrich[grich_all_natrich$site == "McL Ann",]))

# McL Serp
summary(glmer(meanrich ~ year + (1|plot), family = "poisson",  
              data = grich_all_natrich[grich_all_natrich$site == "McL Serp",]))

# Swanton
summary(glmer(meanrich ~ year + (1|plot), family = "poisson",  
              data = grich_all_natrich[grich_all_natrich$site == "Swanton",]))

# UCSC
summary(glmer(meanrich ~ year + (1|plot), family = "poisson",  
            data = grich_all_natrich[grich_all_natrich$site == "UCSC",]))

```

```{r EXOTIC RICHNESS MODELS}
grich_all_exorich <- grich_all %>%
  filter(guild == "Exo") %>%
  mutate(year2 = year,
         # we rescale the year to improve the model and prevent eigenvalue warnings
         year = abs(year2-1983))
grich_all_exorich$year <- as.numeric(grich_all_exorich$year)

# Angelo
summary(glmer(meanrich ~ year + (1|plot), family = "poisson",  
              data = grich_all_exorich[grich_all_exorich$site == "Angelo",]))

# Carrizo - has a problem, inconsistent plots -- ignore data for now
coef(summary(lmer(meanrich ~ year + (1|plot), 
              data = grich_all_exorich[grich_all_exorich$site == "Carrizo",])))

# Elkhorn
summary(glm(meanrich ~ year, family = "poisson",  
              data = grich_all_exorich[grich_all_exorich$site == "Elkhorn",]))

# Jasper
summary(glm(meanrich ~ year, family = "poisson", 
              data = grich_all_exorich[grich_all_exorich$site == "Jasper",]))

# McL Ann
summary(glm(meanrich ~ year, family = "poisson", 
              data = grich_all_exorich[grich_all_exorich$site == "McL Ann",]))

# McL Serp
summary(glm(meanrich ~ year, family = "poisson",  
              data = grich_all_exorich[grich_all_exorich$site == "McL Serp",]))

# Swanton
summary(glm(meanrich ~ year, family = "poisson", 
              data = grich_all_exorich[grich_all_exorich$site == "Swanton",]))


# UCSC
summary(glm(meanrich ~ year, family = "poisson",
            data = grich_all_exorich[grich_all_exorich$site == "UCSC",]))

```

# Shannon Diversity Index

```{r shannon prep and summary graphs, echo = FALSE}
## Angelo
div_ang <- raw_ang %>%
  select(year, site, plot, species.name, cover) %>%
  spread(species.name, cover) %>%
  ungroup()
div_ang_H <- div_ang %>%
  select(-year, -site, -plot)
div_ang_H[is.na(div_ang_H)] <- 0

ang_H <- diversity(div_ang_H, "shannon")
ang_H <- as.data.frame(ang_H) %>% rename('shannon' = 'ang_H')
div_ang <- bind_cols(div_ang, ang_H)  %>%
  select(year, site, plot, shannon)
div_ang$plot <- as.factor(div_ang$plot)

## Carrizo
div_car <- raw_car %>%
  filter(species.name != "litter",
         species.name != "bare",
         species.name != "hole",
         species.name != "moss") %>%
  filter(plot != "SC5" | plot != "SC4") %>%
  select(year, site, plot, species.name, Intercepts) %>%
  spread(species.name, Intercepts) %>%
  ungroup()
div_car_H <- div_car %>%
  select(-year, -site, -plot)
div_car_H[is.na(div_car_H)] <- 0

car_H <- diversity(div_car_H, "shannon")
car_H <- as.data.frame(car_H) %>% rename('shannon' = 'car_H')
div_car <- bind_cols(div_car, car_H)  %>%
  select(year, site, plot, shannon)
div_car$plot <- as.factor(div_car$plot)


## Elkhorn
div_elk <- raw_elk %>%
  filter(species.name != "Moss",
         species.name != "Thatch",
         species.name != "Bare ground") %>%
  mutate(site = "Elkhorn") %>%
  rename(plot = rep) %>%
  select(year, site, plot, species.name, intercepts) %>%
  spread(species.name, intercepts) %>%
  ungroup()
div_elk_H <- div_elk %>%
  select(-year, -site, -plot)
div_elk_H[is.na(div_elk_H)] <- 0

elk_H <- diversity(div_elk_H, "shannon")
elk_H <- as.data.frame(elk_H) %>% rename('shannon' = 'elk_H')
div_elk <- bind_cols(div_elk, elk_H)  %>%
  select(year, site, plot, shannon)
div_elk$plot <- as.factor(div_elk$plot)

## Jasper
div_jasp <- raw_jasp %>%
  filter(cover > 0) %>%
  mutate(site = "Jasper") %>%
  rename('plot' = 'uniqueID') %>%
  select(year, site, plot, species.name, cover) %>%
  spread(species.name, cover) %>%
  ungroup()
div_jasp_H <- div_jasp %>%
  select(-year, -site, -plot)
div_jasp_H[is.na(div_jasp_H)] <- 0

jasp_H <- diversity(div_jasp_H, "shannon")
jasp_H <- as.data.frame(jasp_H) %>% rename('shannon' = 'jasp_H')
div_jasp <- bind_cols(div_jasp, jasp_H)  %>%
  select(year, site, plot, shannon)
div_jasp$plot <- as.factor(div_jasp$plot)

## mcL ann
div_mcLann <- raw_mcLann %>%
  filter(cover > 0) %>%
  filter(species.name != "Bare",
         species.name != "Rock",
         species.name != "Unknown grass",
         species.name != "Unknown forb") %>%
  mutate(site = "McL Ann") %>%
  select(year, site, plot, species.name, cover) %>%
  spread(species.name, cover) %>%
  ungroup()
div_mcLann_H <- div_mcLann %>%
  select(-year, -site, -plot)
div_mcLann_H[is.na(div_mcLann_H)] <- 0

mcLann_H <- diversity(div_mcLann_H, "shannon")
mcLann_H <- as.data.frame(mcLann_H) %>% rename('shannon' = 'mcLann_H')
div_mcLann <- bind_cols(div_mcLann, mcLann_H)  %>%
  select(year, site, plot, shannon)
div_mcLann$plot <- as.factor(div_mcLann$plot)


## mcL serp
div_mcLserp <- raw_mcLserp %>%
  filter(cover > 0) %>%
  filter(species.name != "Bare",
         species.name != "Rock",
         species.name != "Unknown forb") %>%
  mutate(site = "McL Serp") %>%
  select(year, site, plot, species.name, cover) %>%
  spread(species.name, cover) %>%
  ungroup()
div_mcLserp_H <- div_mcLserp %>%
  select(-year, -site, -plot)
div_mcLserp_H[is.na(div_mcLserp_H)] <- 0

mcLserp_H <- diversity(div_mcLserp_H, "shannon")
mcLserp_H <- as.data.frame(mcLserp_H) %>% rename('shannon' = 'mcLserp_H')
div_mcLserp <- bind_cols(div_mcLserp, mcLserp_H)  %>%
  select(year, site, plot, shannon)
div_mcLserp$plot <- as.factor(div_mcLserp$plot)


## swanton
div_swan <- raw_swan %>%
  filter(species.name != "Moss",
         species.name != "Thatch",
         species.name != "Bare ground") %>%
  mutate(site = "Swanton") %>%
  rename('plot' = 'rep') %>%
  select(year, site, plot, species.name, intercepts) %>%
  spread(species.name, intercepts) %>%
  ungroup()
div_swan_H <- div_swan %>%
  select(-year, -site, -plot)
div_swan_H[is.na(div_swan_H)] <- 0

swan_H <- diversity(div_swan_H, "shannon")
swan_H <- as.data.frame(swan_H) %>% rename('shannon' = 'swan_H')
div_swan <- bind_cols(div_swan, swan_H)  %>%
  select(year, site, plot, shannon)
div_swan$plot <- as.factor(div_swan$plot)

## ucsc
div_ucsc <- raw_ucsc %>%
  filter(species.name != "Thatch",
         species.name != "Bare ground") %>%
  mutate(site = "UCSC") %>%
  rename('plot' = 'rep') %>%
  select(year, site, plot, species.name, intercepts) %>%
  spread(species.name, intercepts) %>%
  ungroup()
div_ucsc_H <- div_ucsc %>%
  select(-year, -site, -plot)
div_ucsc_H[is.na(div_ucsc_H)] <- 0

ucsc_H <- diversity(div_ucsc_H, "shannon")
ucsc_H <- as.data.frame(ucsc_H) %>% rename('shannon' = 'ucsc_H')
div_ucsc <- bind_cols(div_ucsc, ucsc_H)  %>%
  select(year, site, plot, shannon)
div_ucsc$plot <- as.factor(div_ucsc$plot)


## combine all 
div_all <- full_join(div_ang, div_car)
div_all <- full_join(div_all, div_elk)
div_all <- full_join(div_all, div_jasp)
div_all <- full_join(div_all, div_mcLann)
div_all <- full_join(div_all, div_mcLserp)
div_all <- full_join(div_all, div_swan)
div_all <- full_join(div_all, div_ucsc)

div_all_means <- div_all %>%
  group_by(year, site) %>%
  summarise(meanH = mean(shannon),
            seH = std.error(shannon))

ggplot(div_all_means, aes(x = year, y = meanH, color = site)) +
  geom_point() +
  geom_line (alpha = 0.5) +
  geom_errorbar(aes(ymin = meanH-seH, ymax = meanH+seH)) +
  labs(title = "All sites - Shannon H over time",
       x = "Year",
       y = "Shannon H") +
  theme_bw() +
  scale_y_continuous(limits = c(0,NA)) + 
  expand_limits(y = 0) +
  facet_wrap(~site, scales = "free", ncol = 4)

```

```{r Shannon H MODELS}
div_all$year <- as.numeric(div_all$year)

# Angelo
summary(glm(shannon ~ year, 
            data = div_all[div_all$site == "Angelo",]))

# Carrizo -- LOOKS WEIRD?
summary(glm(shannon ~ year, 
            data = div_all[div_all$site == "Carrizo",]))

# Elkhorn
summary(glm(shannon ~ year, 
            data = div_all[div_all$site == "Elkhorn",]))

# Jasper
summary(glm(shannon ~ year, 
            data = div_all[div_all$site == "Jasper",]))

# McL Ann
summary(glm(shannon ~ year, 
            data = div_all[div_all$site == "McL Ann",]))

# McL Serp
summary(glm(shannon ~ year, 
            data = div_all[div_all$site == "McL Serp",]))

# Swanton
summary(glm(shannon ~ year, 
            data = div_all[div_all$site == "Swanton",]))


# UCSC
summary(glm(shannon ~ year, 
            data = div_all[div_all$site == "UCSC",]))
```


# Grouped Turnover Graph

```{r turnover, echo=FALSE}
## missing Carrizo because that data isn't taken in the same plots every year

ang_turnover <- turnover(df = rel_all[rel_all$site == "Angelo",],
                          time.var = "year",
                          species.var = "species.name",
                          abundance.var = "relcov",
                          replicate.var = "plot") %>%
  mutate(site = "Angelo")

car_turnover <- turnover(df = rel_all[rel_all$site == "Carrizo",],
                          time.var = "year",
                          species.var = "species.name",
                          abundance.var = "relcov",
                          replicate.var = "plot") %>%
  mutate(site = "Carrizo")

elk_turnover <- turnover(df = rel_all[rel_all$site == "Elkhorn",],
                          time.var = "year",
                          species.var = "species.name",
                          abundance.var = "relcov",
                          replicate.var = "plot") %>%
  mutate(site = "Elkhorn") 

ucsc_turnover <- turnover(df = rel_all[rel_all$site == "UCSC",],
                          time.var = "year",
                          species.var = "species.name",
                          abundance.var = "relcov",
                          replicate.var = "plot") %>%
  mutate(site = "UCSC")

swan_turnover <- turnover(df = rel_all[rel_all$site == "Swanton",],
                          time.var = "year",
                          species.var = "species.name",
                          abundance.var = "relcov",
                          replicate.var = "plot") %>%
  mutate(site = "Swanton") 

jasp_turnover <- turnover(df = rel_all[rel_all$site == "Jasper",],
                          time.var = "year",
                          species.var = "species.name",
                          abundance.var = "relcov",
                          replicate.var = "plot") %>%
  mutate(site = "Jasper") 

McLAnn_turnover <- turnover(df = rel_all[rel_all$site == "McL Ann",],
                          time.var = "year",
                          species.var = "species.name",
                          abundance.var = "relcov",
                          replicate.var = "plot") %>%
  mutate(site = "McL Ann")

mcLserp_turnover <- turnover(df = rel_all[rel_all$site == "McL Serp",],
                          time.var = "year",
                          species.var = "species.name",
                          abundance.var = "relcov",
                          replicate.var = "plot") %>%
  mutate(site = "McL Serp")

all_turnover <- full_join(ang_turnover, car_turnover)
all_turnover <- full_join(all_turnover, elk_turnover)
all_turnover <- full_join(all_turnover, ucsc_turnover)
all_turnover <- full_join(all_turnover, swan_turnover)
all_turnover <- full_join(all_turnover, jasp_turnover)
all_turnover <- full_join(all_turnover, mcLserp_turnover)
all_turnover <- full_join(all_turnover, McLAnn_turnover)

remove(ang_turnover)
remove(car_turnover)
remove(elk_turnover)
remove(ucsc_turnover)
remove(jasp_turnover)
remove(mcLserp_turnover)
remove(McLAnn_turnover)

all_turnover <- all_turnover %>%
  rename(turnover = total) 

all_turn_weather <- left_join(all_turnover, wtryr_weather, by = c("year", "site"))

all_turn_means <- all_turn_weather %>%
  group_by(site, year) %>%
  summarise(meanturn = mean(turnover),
            seturn = std.error(turnover),
            precip = mean(precip),
            tmean = mean(tmean),
            tmax = mean(tmax),
            tmin = mean(tmin))

all_turn_means_lump <- all_turn_weather %>%
  group_by(site) %>%
  summarise(meanturn = mean(turnover),
            seturn = std.error(turnover),
            meanprecip = mean(precip),
            seprecip = std.error(precip),
            tmean = mean(tmean),
            tmax = mean(tmax),
            tmin = mean(tmin))

gcov_ann <- gcov_all %>%
  group_by(site, guild) %>%
  summarise(serelcov = (std.error(meancov)),
            meanrelcov = mean(meancov)) %>%
  filter(guild == "Ann") %>%
  summarise(serelcov = (std.error(meanrelcov)),
            meancov = mean(meanrelcov))

all_turn_means_lump <- left_join(all_turn_means_lump, gcov_ann)
```

```{r turnover graphs, echo = FALSE}
ggplot(all_turn_means, aes(x = site, y = meanturn, color = site)) +
  geom_boxplot() +
  labs(title = "Community turnover by site",
     x = "Site",
     y = "Turnover (New + Lost Species / Total Species)") +
  theme_classic() +
  theme(legend.position = "none") +
  stat_smooth(method = "lm", se = F, size =  1)

ggplot(all_turn_means, aes(x = precip, y = meanturn)) +
  geom_point() +
  geom_errorbar(aes(ymin = meanturn-seturn, ymax = meanturn+seturn)) +
  labs(title = "Community turnover by water year precip",
     x = "Mean water-year precipitation (mm) during study years",
     y = "Turnover)") +
  theme_classic() +
  theme(legend.position = "none") +
  stat_smooth(method = "lm", se = F, size =  1)

grid.arrange(
  ggplot(all_turn_means, aes(x = year, y = meanturn, color = site)) +
    geom_line() +
    geom_errorbar(aes(ymin = meanturn-seturn, ymax = meanturn+seturn)) +
    labs(title = "Community turnover over time",
         x = "Year",
         y = "Turnover (# spp. lost & gained/total # spp.)") +
    facet_wrap(~site, ncol = 4, scale = "free") +
    theme(legend.position = "none"),
  
  ggplot(all_turn_means_lump, aes(x = meanprecip, y = meanturn, color = site)) +
    geom_point() +
    geom_errorbar(aes(ymin = meanturn-seturn, ymax = meanturn+seturn)) +
    geom_errorbarh(aes(xmin = meanprecip-seprecip, xmax = meanprecip+seprecip, height = 0)) +
    labs(title = "Community turnover vs MAP",
         x = "Mean Annual Precipitation",
         y = "Turnover") +
    scale_x_continuous(limits = c(0,2000), expand = c(0,0)) +
    scale_y_continuous(limits = c(0,0.7), expand = c(0,0)) +
    theme(legend.position = "top"),
  
  ggplot(all_turn_means_lump, aes(x = meancov, y = meanturn, color = site)) +
    geom_point() +
    labs(title = "Community turnover vs. proportion annuals",
         x = "Mean cover of annual species",
         y = "Turnover") +
    scale_x_continuous(limits = c(0,1), expand = c(0,0)) +
    scale_y_continuous(limits = c(0,0.7), expand = c(0,0)) +
    theme(legend.position = "none")
)

```

```{r simple lm for turnover vs. MAP}
summary(glm(turnover ~ precip,  
              data = all_turn_models))
```

```{r site-level change in turnover over time}
all_turn_models <- all_turn_weather %>%
  mutate(year2 = year,
         # we rescale the year to improve the model and prevent eigenvalue warnings
         year = abs(year2-1983))
all_turn_models$year <- as.numeric(all_turn_models$year)

# Angelo
summary(glm(turnover ~ year,
              data = all_turn_models[all_turn_models$site == "Angelo",]))

# Carrizo - has a problem, inconsistent plots -- ignore data for now
summary(glm(turnover ~ year,
              data = all_turn_models[all_turn_models$site == "Carrizo",]))

# Elkhorn
summary(glm(turnover ~ year,
              data = all_turn_models[all_turn_models$site == "Elkhorn",]))

# Jasper
summary(glm(turnover ~ year,
              data = all_turn_models[all_turn_models$site == "Jasper",]))

# McL Ann
summary(glm(turnover ~ year,
              data = all_turn_models[all_turn_models$site == "McL Ann",]))

# McL Serp
summary(glm(turnover ~ year,
              data = all_turn_models[all_turn_models$site == "McL Serp",]))

# Swanton
summary(glm(turnover ~ year,
              data = all_turn_models[all_turn_models$site == "Swanton",]))

# UCSC
summary(glm(turnover ~ year,
              data = all_turn_models[all_turn_models$site == "UCSC",]))
```



# Changes in CTI over time

Here, we'll try to analyze CTI for all of the sites at once. 

```{r import CTI data}
CTI_all <- read.csv("Analysis/CTI Data/AllSite_CTI_08_2020.csv")
  
CTI_all <- CTI_all %>%
  filter(species.name != "Linanthus jepsonii",
         species.name != "Linanthus latisectus")

CTI_all <- CTI_all %>%
  filter(relcov >= 0) %>%
  group_by(site, year, plot) %>%
  mutate(relCTI = relcov*meanT,
         relCPI = relcov*meanp) %>%
  summarise(plotCTI = sum(relCTI),
            plotCPI = sum(relCPI))
```

```{r summarizing at plot level}
CTI_plot_means <- CTI_all %>%
  group_by(site, plot, year) %>%
  summarise(meanCTI = mean(plotCTI),
            seCTI = std.error(plotCTI),
            meanCPI = mean(plotCPI),
            seCPI = std.error(plotCPI))

CTI_site_means <- CTI_all %>%
  group_by(site, year) %>%
  summarise(meanCTI = mean(plotCTI),
            seCTI = std.error(plotCTI),
            meanCPI = mean(plotCPI),
            seCPI = std.error(plotCPI))

ggplot(CTI_site_means, aes(x = year, y = meanCTI, color = site)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = (meanCTI - seCTI), ymax = (meanCTI + seCTI))) +
  labs(title = "All sites - Community Temperature Index",
       x = "Year",
       y = "CTI") +
  theme_bw() +
  theme(legend.position = "none") +
  facet_wrap(~site, scales = "free", ncol = 4) + geom_smooth(method = "lm")
  
ggplot(CTI_site_means, aes(x = year, y = meanCPI, color = site)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = (meanCPI - seCPI), ymax = (meanCPI + seCPI))) +
  labs(title = "All sites - Community Precipitation Index",
       x = "Year",
       y = "CPI") +
  theme_bw() +
  theme(legend.position = "none") +
  facet_wrap(~site, scales = "free", ncol = 4) + geom_smooth(method = "lm")

```

```{r CTI MODELS}
CTI_models <- CTI_plot_means %>%
  mutate(year2 = year,
         # we rescale the year to improve the model and prevent eigenvalue warnings
         year = abs(year2-1983))
CTI_models$year <- as.numeric(CTI_models$year)

# Angelo
summary(glm(meanCTI ~ year,
              data = CTI_models[CTI_models$site == "Angelo",]))

# Carrizo - has a problem, inconsistent plots -- ignore data for now
summary(glm(meanCTI ~ year,
              data = CTI_models[CTI_models$site == "Carrizo",]))

# Elkhorn
summary(glm(meanCTI ~ year,
              data = CTI_models[CTI_models$site == "Elkhorn",]))

# Jasper
summary(glm(meanCTI ~ year,
              data = CTI_models[CTI_models$site == "Jasper",]))

# McL Ann
summary(glm(meanCTI ~ year,
              data = CTI_models[CTI_models$site == "McL Ann",]))

# McL Serp
summary(glm(meanCTI ~ year,
              data = CTI_models[CTI_models$site == "McL Serp",]))

# Swanton
summary(glm(meanCTI ~ year,
              data = CTI_models[CTI_models$site == "Swanton",]))

# UCSC
summary(glm(meanCTI ~ year,
              data = CTI_models[CTI_models$site == "UCSC",]))
```

```{r CPI MODELS}
CPI_models <- CTI_plot_means %>%
  mutate(year2 = year,
         # we rescale the year to improve the model and prevent eigenvalue warnings
         year = abs(year2-1983))
CPI_models$year <- as.numeric(CPI_models$year)

# Angelo
summary(glm(meanCPI ~ year,
              data = CPI_models[CPI_models$site == "Angelo",]))

# Carrizo - has a problem, inconsistent plots -- ignore data for now
summary(glm(meanCPI ~ year,
              data = CPI_models[CPI_models$site == "Carrizo",]))

# Elkhorn
summary(glm(meanCPI ~ year,
              data = CPI_models[CPI_models$site == "Elkhorn",]))

# Jasper
summary(glm(meanCPI ~ year,
              data = CPI_models[CPI_models$site == "Jasper",]))

# McL Ann
summary(glm(meanCPI ~ year,
              data = CPI_models[CPI_models$site == "McL Ann",]))

# McL Serp
summary(glm(meanCPI ~ year,
              data = CPI_models[CPI_models$site == "McL Serp",]))

# Swanton
summary(glm(meanCPI ~ year,
              data = CPI_models[CPI_models$site == "Swanton",]))

# UCSC
summary(glm(meanCPI ~ year,
              data = CPI_models[CPI_models$site == "UCSC",]))
```

## CTI vs actual temp
```{r adding weather}
wtryr_weather <- read.csv("Analysis/ClimData/PRISM_wtryr_data.csv") %>%
  select(-X)
```

```{r join CTI/temp}
CTI_Clim_Rich <- left_join(CTI_site_means, wtryr_weather)
CTI_Clim_Rich <- left_join(CTI_Clim_Rich, grich_all_means)

ggplot(CTI_Clim_Rich, aes(x = tmean, y = meanCTI, color = site)) +
  geom_point() +
  theme_bw() +
  theme(legend.position = "none") +
  facet_wrap(~site, scales = "free", ncol = 4) + 
  geom_smooth(method = "lm", alpha = 0.5, aes(color = site))

ggplot(CTI_Clim_Rich, aes(x = precip, y = meanCPI, color = site)) +
  geom_point() +
  theme_bw() +
  theme(legend.position = "none") +
  facet_wrap(~site, scales = "free", ncol = 4) + 
  geom_smooth(method = "lm", alpha = 0.5, aes(color = site))

ggplot(CTI_Clim_Rich, aes(x = tmin, y = meanCPI, color = site)) +
  geom_point() +
  theme_bw() +
  theme(legend.position = "none") +
  geom_smooth(method = "lm", alpha = 0.5, aes(color = site))

ggplot(CTI_Clim_Rich, aes(x = meanrich, y = meanCTI, color = site)) +
  geom_point() +
  theme_bw() +
  theme(legend.position = "none") +
  facet_wrap(~site, scales = "free", ncol = 4) + 
  geom_smooth(method = "lm", alpha = 0.5, aes(color = site))
```

