---
title: "Main figures"
date: "`r format(Sys.time(), '%B %d, %Y')`"
editor_options: 
  chunk_output_type: console
output:
  bookdown::html_document2: 
    fig_caption: true
    number_sections: true
    global_numbering: true
  bookdown::word_document2: 
    fig_caption: true
    number_sections: true
    global_numbering: true
---

```{r setup, echo=FALSE, message=FALSE}
source("scripts/_setup.R")
```

```{r niche-fig, fig.width=8, fig.height=8*1.618}
#| fig.cap = "Grassland species occur along geographic and climatic gradients to estimate ecological niches.
#|  (A) Occurrence of grassland species in California Floristic Province, retrieved from the GBIF data (gray points), highlighting two example species *Danthonia californica* in the north (blue points) and *Stipa pulchra* in the south (red points).
#|  (B) Species occurrence in climate space of mean annual temperature (°C) and mean annual precipitation (mm), retrieved from the CHELSA data (gray), highlighting the same two example species *Danthonia californica* under cool and wet climates (blue) and *Stipa pulchra* under warm and dry climates (red).
#|  (C) Ecological niche estimates from average temperature and precipitation for each species (median, gray), highlighting the two species (blue and red)."
source("scripts/plot-main-niche.R")
niche_gg
rm(list = ls())
```

```{r obs-fig, fig.width=11, fig.height=11*1.5}
#| fig.cap = "Grassland community shifts from long-term observations.
#|  Consistent with climate warming and drying, grassland communities shift dominance to warmer (increasing CTI) and drier (decreasing CPI) species in 12 long-term observational sites across the California Floristic Province (red trend lines by linear regression, significant slopes by *t*-test, *p* ≤ 0.05).
#|  The map shows the geographical distribution of the 12 sites with grassland percent cover (green) from Sentinel-2 10 m land use/land cover time series data."
source("scripts/plot-main-obs.R")
obs_gg
rm(list = ls())
```

```{r exp-fig, fig.width=10, fig.height=6.18}
#| fig.cap = "Grassland community shifts from long-term experiments.
#|  Warming treatment causes communities to shift dominance to warmer (CTI, °C) and drier (CPI, mm) species in the Jasper Ridge Global Change Experiment (72 ambient plots in black, 64 warming plots in red, non-parametric two-sample Wilcoxon test, ns: *p* > 0.05, $*$: *p* ≤ 0.05, $**$: *p* ≤ 0.01, $***$: *p* ≤ 0.001).
#|  The orange background shades denote phase I heating +80 W m^–2^ leading to ~ +1 °C warming in 1999-2002, phase II heating +100 W m^–2^ leading to ~ +1.5 °C warming in 2003-2009, and phase III heating +250 W m^–2^ leading to ~ +2 °C warming in 2010-2014."
source("scripts/plot-main-exp.R")
exp_gg
rm(list = ls())
```

```{r shift-fig, fig.width=9, fig.height=9*1.618}
#| fig.cap = "Grassland community shifts synthesized from both observations and experiments.
#|  (A) Community compositions at 12 observational sites (blue) and an experimental site (orange) described by the median Community Temperature Index (CTI, °C) and Community Precipitation Index (CPI, mm), positioned in the ecological niche estimates for individual species (median, gray). The inset rectangle shows the extent of panel B.
#|  (B) Communities shift in a consistent direction in the climate space in observations (blue) and experiment (orange). For the observational sites, arrows point from the start to the end of the sampling period; for the experiment site, arrows point from ambient to warming treatments. The CTI-CPI extent is identical in panel C, whereas an inset rectangle shows the extent of panel D.
#|  (C) Communities shift significantly in eight out of 12 observational sites across the California Floristic Province. For sites with non-significant linear temporal trends in either CTI or CPI, arrows are set to be semi-transparent (*t*-test, *p* ≤ 0.05).
#|  (D) Communities shift significantly, mainly in phase III warming of the Jasper Ridge Global Change Experiment. For years with non-significant differences between the ambient (black) and warming (red) treatments in either CTI or CPI, arrows are set to be semi-transparent (non-parametric two-sample Wilcoxon test, *p* ≤ 0.05)."
source("scripts/plot-main-shift.R")
shift_gg
rm(list = ls())
```

```{r gainloss-fig, fig.width=12, fig.height=12}
#| fig.cap = "Gain and loss of species during grassland community shifts in observations and experiment.
#|  (A) Ecological niches of species with a significant increase in abundance over time (green circle), with a significant decrease in abundance over time (yellow circle), newly recruited (not present at the site in the first five years, green-filled circle), completely lost (not present at the site in the last five years, yellow-filled circle), and all other species present at each observational site (gray) (*t*-test, *p* ≤ 0.05). The size of circles is proportional to the species' dominance in the community.
#|  (B) Ecological niches of species with a significant increase in abundance under warming (green circle), with a significant decrease in abundance under warming (yellow circle), and all other species present in each year of Phase III of the Jasper Ridge Global Change Experiment (gray) (non-parametric two-sample Wilcoxon test, *p* ≤ 0.05). The size of circles is proportional to the species' dominance in the community."
source("scripts/plot-gainloss.R")
gainloss_main_gg
rm(list = ls())
```
