---
title: "Supplementary figures"
date: "`r format(Sys.time(), '%B %d, %Y')`"
editor_options: 
  chunk_output_type: console
output:
  bookdown::html_document2: 
    fig_caption: true
    number_sections: true
    global_numbering: true
  bookdown::word_document2: 
    fig_caption: true
    number_sections: true
    global_numbering: true
---

```{r setup, echo=FALSE, message=FALSE}
source("scripts/_setup.R")
```

```{r cfp-climate-fig, fig.width=12, fig.height=8, eval=FALSE}
#| fig.cap = "Climate change in the California Floristic Province (CFP).
#|  Linear regressions describe trends in (A) mean annual temperature (°C yr^−1^) and (B) total annual precipitation (mm yr^−1^) over the years, from 1980 to 2019, in 30 arc sec (~1 km) resolution, estimated from the CHELSA time series data.
#|  Contour lines surround pixels with statistically significant trends (*t*-test, *p* ≤ 0.05)."
source("scripts/plot-cfp-climate.R")
cfp_clim_gg
rm(list = ls())
```

```{r data-avail-fig, fig.width=10, fig.height=10*.618}
#| fig.cap = "Data availability of the warming experiment and 12 observational sites.
#|  The green lines indicate the start and the end of sampling; black dots show in which years sampling was conducted."
source("scripts/plot-data-avail.R")
data_avail_gg
rm(list = ls())
```

```{r obs-site-climate-fig, fig.width=11, fig.height=11*1.5}
#| fig.cap = "Climate change in observational sites. Mean annual temperature (°C) and total annual precipitation (mm) are extracted from the CHELSA monthly time series from 1980 to 2019, highlighting the sampling periods in the observational periods.
#|  Trends are summarized by regression lines, solid *p* ≤ 0.05, dashed *p* > 0.05 (*t*-test).
#|  The map shows the geographical distribution of the 12 sites with grassland percent cover (green) from Sentinel-2 10 m land use/land cover time series data."
source("scripts/plot-site-climate.R")
site_clim_gg
rm(list = ls())
```

```{r occ-data-fig, fig.width=10, fig.height=7, eval=FALSE}
#| fig.cap = "Occurrence data comparison from multiple sources in CFP.
#|  BIEN: Botanical Information and Ecology Network, CCH: Consortium of California Herbaria, GBIF: Global Biodiversity Information Facility, iNat: iNaturalist.
#|  Randomly showing 10% of data points to avoid overplotting."
source("scripts/compare-occ-data.R")
occ_comp_gg
rm(list = ls())
```

```{r clim-data-fig, fig.width=10, fig.height=10}
#| fig.cap = "Climate data comparison from multiple sources in the CFP: CHELSA, PRISM, and TerraClimate.
#|  Each point corresponds to a GBIF occurrence location.
#|  Brighter colors of hexagons indicate a greater number of data points.
#|  Solid is the 1:1 line, and dashed is the regression line, where statistics (correlation coefficient *R* and *p*-value) are reported on the top left."
source("scripts/compare-clim-data.R")
clim_comp_gg
rm(list = ls())
```

```{r tmp-niche-fig, fig.width=7, fig.height=7}
#| fig.cap = "Species temperature niche statistics.
#|  Distributions across species are shown by diagonal histograms, and pairwise correlations are visualized by lower-diagonal scatter plots and quantified by upper-diagonal correlation coefficients with *t*-tests (ns: *p* > 0.05, $*$: *p* ≤ 0.05, $**$: *p* ≤ 0.01, $***$: *p* ≤ 0.001)."
source("scripts/compare-niche-stat.R")
niche_tmp_gg
```

```{r ppt-niche-fig, fig.width=7, fig.height=7}
#| fig.cap="Species precipitation niche statistics. Symbols follow the previous figure."
niche_ppt_gg
rm(list = ls())
```

```{r thin-fig, fig.width=10, fig.height=7}
#| fig.cap = "Species climate niche estimates from full and thinned datasets.
#|  Each point corresponds to the median temperature or precipitation for a species.
#|  Solid is the 1:1 line, and dashed is the regression line, where statistics (correlation coefficient *R* and *p*-value) are reported on the top left."
source("scripts/compare-sp-thin.R")
thin_comp_gg
rm(list = ls())
```

```{r cool-sp-fig, fig.width=8, fig.height=8*.618}
#| fig.cap = "Example species *Danthonia californica* distributions in geographical space and climate space.
#|  The left shows GBIF occurrence records in the CFP.
#|  The right panel shows the number of GBIF records (*n*) and their distribution in reference to mean annual temperature and precipitation from CHELSA data.
#|  The scatters are summarized by axis rugs for marginal distributions and a Gaussian data ellipse at the 95% confidence interval and a centroid cross (median) for the joint distribution."
source("scripts/plot-ind-spp.R")
niche_gg["Danthonia californica"]
```

```{r warm-sp-fig, fig.width=8, fig.height=8*.618}
#| fig.cap = "Example species *Stipa pulchra* distributions in geographical space and climate space.
#|  Symbols follow the last figure."
niche_gg["Stipa pulchra"]
dev.off()
```
