---
title: "Supplementary tables"
date: "`r format(Sys.time(), '%B %d, %Y')`"
editor_options: 
  chunk_output_type: console
output:
  bookdown::html_document2: 
    fig_caption: true
    number_sections: true
    global_numbering: true
  bookdown::word_document2: 
    fig_caption: true
    number_sections: true
    global_numbering: true
---

```{r setup, echo=FALSE, message=FALSE}
source("scripts/_setup.R")
```

```{r site-tab}
#| tab.cap="Information of 12 observational sites with corresponding labels to fig. X."
source("scripts/show-site-info.R")
site_tbl %>%
  flextable::flextable() %>%
  flextable::autofit() %>%
  flextable::fit_to_width(7.5)
rm(list = ls())
```

```{r occ-data-tab, eval=FALSE}
#| tab.cap = "Comparison of occurrence data from multiple sources in the CFP.
#|  BIEN: Botanical Information and Ecology Network, CCH: Consortium of California Herbaria, GBIF: Global Biodiversity Information Facility, iNat: iNaturalist."
source("scripts/compare-occ-data.R")
knitr::kable(occ_samp_tbl, caption = "Comparison of occurrence datasets.")
rm(list = ls())
```

```{r obs-tmp-tab}
#| tab.cap = "Observational site climate change---temperature."
```

```{r obs-ppt-tab}
#| tab.cap = "Observational site climate change---precipitation"
```

```{r obs-cti-tab}
```

```{r obs-cpi-tab}
```

```{r exp-cti-tab}
```

```{r exp-cpi-tab}
```

```{r exp-lme-tab}
```

```{r gainloss-tab}
```
