---
title: "3 Taxonomy"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_knit$set(root.dir = here::here()) # knit from project directory
knitr::opts_chunk$set(
  collapse = TRUE,
  out.width = "100%",
  cache = T,
  comment = "#>",
  fig.width = 8,
  fig.height = 8
)
```

```{r setup}
library(grassland)
theme_set(ggthemes::theme_few())
```

Save a species list from all tidy data
```{r, eval=F}
f_species_tidy <- tidy_taxonomy_list(dat_community_tidy)
```

Josie and Justin used the output for manual correction, producing "misspelling.csv".
```{r}
read_csv("alldata/input/community/species/misspelling.csv") %>% head(20) %>% knitr::kable() 
```

Rename species
```{r, eval = F}
path_community <- tidy_taxonomy_rename()
dat_community <- read_community(version = "final")
```

```{r}
dat_community
```

Josie and Justin made "consolidation.csv", where old species names are later used for querying biogeography data and new species names (onsolidated names) are used in this analysis.
```{r}
read_csv("alldata/input/community/species/consolidation.csv") %>% head(20) %>% knitr::kable()
```

Output figures and r data files
```{r, eval = F}
save_rda(out = list(dat_community))
```

