---
title: "Vignette_release"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette_release}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_knit$set(root.dir = here::here()) # knit from project directory
knitr::opts_chunk$set(
  collapse = TRUE,
  out.width = "100%",
  fig.width = 10,
  fig.height = 10,
  cache = T,
  comment = "#>"
)
```

```{r setup}
library(grassland)
theme_set(ggthemes::theme_few())
```

Load community composition data (experimental and observational).
```{r}
dat_community
```

```{r}
dat_occ$gbif
# dat_clim
dat_trait
```

Calculate species niche and plot
```{r}
dat_niche <- calc_species_niche(dat_trait, add_dummy = T)

gg_individual_trait_species_niche_cool <- plot_individual_trait_species_niche_ind_sp(dat_occ, dat_trait, sp = "Danthonia californica")
gg_individual_trait_species_niche_warm <- plot_individual_trait_species_niche_ind_sp(dat_occ, dat_trait, sp = "Stipa pulchra")
gg_individual_trait_species_niche_cool
gg_individual_trait_species_niche_warm

gg_species_niche <- plot_species_niche(dat_niche,
  cool_species = "Danthonia californica",
  warm_species = "Stipa pulchra"
)
gg_species_niche
```

Calculate CTI CPI in observations and experiments and plot

```{r}
dat_index <- calc_community_index(dat_niche = dat_niche, dat_community = dat_community)
gg_community_index_obs <- plot_community_index(option = "obs", dat_index = dat_index)
gg_community_index_obs
gg_community_index_exp <- plot_community_index(option = "exp", dat_index = dat_index)
gg_community_index_exp
```

Statistical test of trait change using lme
```{r}
df_test_trait_change_obs <- test_trait_change_all(dat_community, dat_niche, type = "obs")
df_test_trait_change_obs %>% knitr::kable()
df_test_trait_change_exp <- test_trait_change_all(dat_community, dat_niche, type = "exp")
df_test_trait_change_exp %>% knitr::kable()
```

Synthesize coupled CTI CPI change
```{r}
dat_shift <- calc_community_shift(dat_index = dat_index)
gg_community_shift <- plot_community_shift(dat_shift, dat_niche)
gg_community_shift$obs
gg_community_shift$exp
gg_community_shift$compare
```

Analysis of species contributing to CTI CPI change
```{r}
dat_gainloss <- calc_species_gainloss(dat_community = dat_community, dat_niche = dat_niche)
gg_species_gainloss <- plot_species_gainloss(dat_niche = dat_niche, dat_gainloss = dat_gainloss)
gg_species_gainloss$obs$circle_detail
gg_species_gainloss$exp$circle_detail
```
