---
title: "CTI Supplmental"
author: "Josie Lesage"
date: "7/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## community analysis
library(codyn)
library(MASS)
library(vegan)
library(lme4)

## CTI analysis
library(CoordinateCleaner)
library(countrycode)
library(mapr)
library(maptools)
library(raster)
library(rgbif)
library(scrubr)
library(sp)
library(spocc)

## misc/both/other
library(oz)
library(plotrix)
library(tidyverse)
library(gridExtra)
```

For CTI or CPI to be valid measures, we want to see that the histograms of species-specific thermal and precipitation index values.

```{r call all species}
rel_all <- read.csv("Analysis/ComData/AllData_Relative.csv")

all_species <- unique(rel_all$species.name)
all_species <- as.data.frame(all_species)
all_species <- all_species %>%
  mutate(all_species.2 = str_squish(all_species)) %>%
  select(-all_species) %>% rename(all_species = all_species.2)
all_species$all_species <- paste0("'", all_species$all_species, "',")
cat(format_delim(all_species, delim = ""))

all_species_list <- c('Danthonia californica',
'Bromus hordeaceus',
'Bromus tectorum',
'Bromus diandrus',
'Aira caryophyllea',
'Briza minor',
'Cynosurus echinatus',
'Vulpia myuros',
'Avena barbata',
'Dichelostemma capitatum',
'Brodiaea elegans',
'Eschscholzia californica',
'Sanicula bipinnatifida',
'Rumex acetosella',
'Convolvulus arvensis',
'Torilis arvensis',
'Daucus pusillus',
'Lotus micranthus',
'Lotus wrangelianus',
'Lupinus bicolor',
'Galium parisiense',
'Madia gracilis',
'Hypochaeris glabra',
'Castilleja attenuata',
'Aphanes occidentalis',
'Linanthus bicolor',
'Trichostema lanceolatum',
'Eremocarpus setigerus',
'Geranium dissectum',
'Epilobium brachycarpum',
'Clarkia purpurea',
'Plagiobothrys nothofulvus',
'Cerastium glomeratum',
'Erodium cicutarium',
'Hemizonia congesta',
'Bromus hordeaceus',
'Bromus madritensis ssp rubens',
'Calandrinia ciliata',
'Dichelostemma capitatum',
'Erodium cicutarium',
'Hordeum murinum',
'Poa secunda ssp secunda',
'Schismus arabicus',
'Vulpia microstachys v pauciflora',
'Vulpia myuros v hirsuta',
'Amsinckia tessellata',
'Athysanus pusillus',
'Guillenia lasiophylla',
'Lasthenia californica',
'Lepidium nitidum',
'Phlox gracilis',
'Trifolium gracilentum',
'Tropidocarpum gracile',
'Pectocarya penicillata',
'Sisymbrium irio',
'Lasthenia minor',
'Lotus wrangelianus',
'Malacothrix coulteri',
'Microseris elegans',
'Eriogonum gracillimum',
'Lupinus microcarpus v microcarpus',
'Microseris douglasii',
'Monolopia lanceolata',
'Trichostema lanceolatum',
'Amsinckia menziesii',
'Trifolium albopurpureum',
'Descurainia sophia',
'Capsella bursa-pastoris',
'Astragalus didymocarpus',
'Salsola tragus',
'Lepidium dictyotum',
'Astragalus oxyphysus',
'Astragalus lentiginosus v nigricalycis',
'Phacelia ciliata',
'Amsinckia menziesii v intermedia',
'Monolopia congdonii',
'Marrubium vulgare',
'Chorizanthe watsonii',
'Linanthus liniflorus',
'Herniaria hirsuta ssp. cinerea',
'Plagiobothrys canescens',
'Chorizanthe uniaristata',
'Hollisteria lanata',
'Castilleja exserta',
'Lupinus bicolor',
'Chaenactis glabriuscula v glabriuscula',
'Uropappus lindleyi',
'Vulpia bromoides',
'Lastarriaea coriacea',
'Muilla maritima',
'Plantago erecta',
'Lactuca serriola',
'Camissonia campestris',
'Lasthenia glabrata ssp coulteri',
'Camissonia palmeri',
'Crassula connata',
'Eremocarpus setigerus',
'Delphinium recurvatum',
'Castilleja lineariloba',
'Stephanomeria pauciflora',
'Erodium botrys',
'Geranium dissectum',
'Trifolium dubium',
'Trifolium subterraneum',
'Hypochaeris radicata',
'Plantago lanceolata',
'Rumex acetosella',
'Taraxia ovata',
'Festuca perennis',
'Vulpia myuros',
'Juncus bufonius',
'Isolepis carinata',
'Danthonia californica',
'Briza maxima',
'Bromus diandrus',
'Holcus lanatus',
'Stipa pulchra',
'Juncus occidentalis',
'Juncus phaeocephalus',
'Lysimachia arvensis',
'Trifolium angustifolium',
'Erodium moschatum',
'Avena barbata',
'Cynosurus echinatus',
'Briza minor',
'Vicia sativa',
'Silybum marianum',
'Hypochaeris glabra',
'Carduus pycnocephalus',
'Cerastium glomeratum',
'Phalaris aquatica',
'Brachypodium distachyon',
'Sonchus oleraceus',
'Sonchus asper',
'Agoseris heterophylla',
'Astragalus gambellianus',
'Calycadenia multiglandulosa',
'Chlorogalum pomeridianum',
'Eschscholzia californica',
'Layia platyglossa',
'Linanthus parviflorus',
'Micropus californicus',
'Castilleja densiflora',
'Elymus multisetus',
'Vulpia microstachys',
'Minuartia douglasii',
'Hemizonia congesta',
'Epilobium brachycarpum',
'Hesperevax sparsiflora',
'Poa secunda',
'Gilia clivorum',
'Plagiobothrys nothofulvus',
'Lolium multiflorum',
'Melica californica',
'Bromus berteroanus',
'Lomatium utriculatum',
'Aphanes occidentalis',
'Bromus madritensis',
'Centaurea melitensis',
'Centaurea solstitialis',
'Gilia tricolor',
'Holocarpha virgata',
'Medicago polymorpha',
'Nassella pulchra',
'Navarretia pubescens',
'Petrorhagia prolifera',
'Triphysaria eriantha',
'Velezia rigida',
'Allium serra',
'Avena fatua',
'Clarkia purpurea',
'Claytonia exigua',
'Collinsia heterophylla',
'Dodecatheon hendersonii',
'Galium aparine',
'Gastridium ventricosum',
'Geranium molle',
'Nemophila menziesii',
'Ranunculus occidentalis',
'Rigiopappus leptocladus',
'Senecio vulgaris',
'Taeniatherum caput-medusae',
'Triteleia laxa',
'Bellardia trixago',
'Brassica nigra',
'Castilleja attenuata',
'Poa bulbosa',
'Trifolium hirtum',
'Achyrachaena mollis',
'Vicia villosa',
'Silene gallica',
'Hieracium albiflorum',
'Hordeum marinum',
'Lupinus microcarpus',
'Lupinus succulentus',
'Daucus pusillus',
'Linanthus ciliatus',
'Lotus humistratus',
'Minuartia californica',
'Navarretia viscidula',
'Trifolium microcephalum',
'Calochortus luteus',
'Filago gallica',
'Navarretia tagetina',
'Centaurium trichanthum',
'Polypogon monspeliensis',
'Agoseris grandiflora',
'Euphorbia crenulata',
'Trifolium bifidum',
'Trifolium fucatum',
'Achillea millefolium',
'Allophyllum gilioides',
'Linanthus bicolor',
'Phacelia imbricata',
'Sanicula bipinnatifida',
'Thysanocarpus curvipes',
'Collinsia sparsiflora',
'Madia elegans',
'Trifolium microdon',
'Madia gracilis',
'Trifolium willdenovii',
'Galium murale',
'Plectritis ciliosa',
'Calochortus superbus',
'Lotus micranthus',
'Madia exigua',
'Sisyrinchium bellum',
'Grindelia camporum',
'Sanicula crassicaulis',
'Trifolium obtusiflorum',
'Dactylis glomerata',
'Sidalcea diploscypha',
'Trifolium depauperatum',
'Zigadenus fremontii',
'Lomatium marginatum',
'Anthriscus caucalis',
'Chamomilla suaveolens',
'Lathyrus vestitus',
'Wyethia glabra',
'Astragalus breweri',
'Atriplex triangularis',
'Delphinium variegatum',
'Anagallis arvensis',
'Melilotus indicus',
'Cirsium vulgare',
'Elymus elymoides',
'Lithophragma heterophyllum',
'Sisymbrium officinale',
'Stellaria nitens',
'Delphinium hesperium',
'Sagina apetala',
'Erodium brachycarpum',
'Cryptantha hispidula',
'Camissonia graciliflora',
'Torilis nodosa',
'Ranunculus californicus',
'Sanicula bipinnata',
'Perideridia kelloggii',
'Cardamine oligosperma',
'Claytonia parviflora',
'Aegilops triuncialis',
'Nemophila heterophylla',
'Phalaris paradoxa',
'Mimulus douglasii',
'Rumex crispus',
'Galium porrigens',
'Chorizanthe membranacea',
'Astragalus rattanii var. jepsonianus',
'Elytrigia repens',
'Pectocarya pusilla',
'Navarretia jepsonii',
'Castilleja rubicundula',
'Githopsis specularioides',
'Bromus tectorum',
'Poa annua',
'Trifolium ciliolatum',
'Lupinus albifrons',
'Bromus laevipes',
'Holodiscus discolor',
'Quercus durata',
'Stellaria media',
'Helianthus exilis',
'Ancistrocarphus filagineus',
'Quercus douglasii',
'Quercus lobata',
'Salvia columbariae',
'Eriophyllum lanatum',
'Elymus glaucus',
'Tragopogon dubius',
'Cuscuta californica',
'Cerastium fontanum ssp. vulgare',
'Cercocarpus betuloides',
'Gnaphalium californicum',
'Lomatium dasycarpum',
'Allium amplectens',
'Nassella lepida',
'Nemophila pedunculata',
'Trifolium variegatum',
'Allium fimbriatum',
'Lonicera hispidula',
'Calochortus vestae',
'Calycadenia pauciflora',
'Clarkia gracilis',
'Gilia capitata',
'Eriogonum nudum',
'Lagophylla minor',
'Hesperolinon californicum',
'Viola douglasii',
'Hesperolinon micranthum',
'Hordeum brachyantherum',
'Layia septentrionalis',
'Bromus carinatus',
'Eriogonum vimineum',
'Triphysaria versicolor',
'Lessingia ramulosa',
'Mimulus androsaceus',
'Hesperolinon disjunctum',
'Linanthus jepsonii',
'Allium falcifolium',
'Chorizanthe polygonoides',
'Lotus purshianus',
'Fritillaria pluriflora',
'Asclepias fascicularis',
'Linanthus latisectus',
'Thermopsis macrophylla',
'Melica imperfecta',
'Filago californica',
'Melica torreyana',
'Chaenactis glabriuscula',
'Streptanthus breweri',
'Camissonia ovata',
'Senecio eurycephalus',
'Hordeum depressum',
'Iris douglasiana',
'Lomatium macrocarpum',
'Erythranthe guttata',
'Helianthella californica',
'Scutellaria siphocampyloides',
'Linanthus dichotomus',
'Vulpia octoflora',
'Eriogonum covilleanum',
'Pinus sabiniana',
'Apocynum cannabinum',
'Antirrhinum vexillocalyculatum',
'Eriodictyon californicum',
'Triteleia hyacinthina',
'Adenostoma fasciculatum',
'Trichostema laxum',
'Bromus japonicus',
'Asclepias eriocarpa',
'Rumex pulcher',
'Epilobium ciliatum',
'Hirschfeldia incana')

```

```{r pull gbif data}
all_species_data <- occ(query = all_species_list, from = "gbif", has_coords = TRUE, limit = 10000,
                gbifopts = list(hasGeospatialIssue = FALSE, country = "US",
                                stateProvince = "California"))

```

```{r convert to df}
## we can also replace all synonym taxon names with one (cuts down the number of plotted dot colors)
## we should use the scrubr version of the function in the future
all_species_data <- fixnames(all_species_data, how = "query")

## The occ2df function should convert the data to a dataframe format
all_species_data_df <- occ2df(all_species_data)

## save the df as a .csv
write.csv(all_species_data_df, "Analysis/CTI Data/SpeciesGBIFData.csv")
```


```{r clean data}
# We need to clean the coordinates, as it appears some are in the ocean, and there might be some that are just incorrect. To do this, we will use a coordinate cleaner package.
flags <- clean_coordinates(x = all_species_data_df, lon = "longitude", lat = "latitude",
                          species = "name",
                          tests = c("capitals", "centroids", "equal","gbif", "institutions",
                                    "seas", "zeros", "duplicates")) # most tests are on by default

# Most of our flagged coordinates are coastal/in the ocean. Therefore, we'll remove them from our database.
# keep only the non-flagged data
all_species_data_df <- all_species_data_df[flags$.summary,] %>%
  rename("species.name" = "name")

```

```{r extracting coords and climate data}
xy <- all_species_data_df[,c("longitude","latitude")]
sp_xy <- all_species_data_df[c("species.name", "longitude","latitude")]

env <- getData('worldclim', var='bio', res=2.5)

xy_bio <- raster::extract(env, xy)

all_species_climate <- cbind(xy_bio, sp_xy) %>%
  dplyr::select(species.name, latitude, longitude, bio1, bio12) %>%
  filter(!is.na(bio1)) %>%
  mutate(bio1 = bio1/10)
```


```{r histograms}
# temperature histogram
ggplot(all_species_climate, aes(bio1)) +
  facet_wrap(~species.name, scales = "free") +
  geom_histogram()

ggplot(all_species_climate, aes(bio12)) +
  facet_wrap(~species.name, scales = "free") +
  geom_histogram()
```

