---
title: "Combining Analyses for Lab Meeting"
author: "Josie Lesage"
date: "12/7/2019"
output: html_document
---

# Setup and data import
```{r setup, include=FALSE}
## community analysis
library(codyn)
library(MASS)
library(lme4)
library(nlme)


## misc/both/other
library(oz)
library(plotrix)
library(tidyverse)
library(gridExtra)


# to rip legends out of figures
g_legend <- function(a.gplot){ 
    tmp <- ggplot_gtable(ggplot_build(a.gplot)) 
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box") 
    legend <- tmp$grobs[[leg]] 
    legend
} 
```

```{r com data import, echo=FALSE}
elkhorn_data <- read.csv("Analysis/ComData/elkhorn_data.csv")

mcLserp_data <- read.csv("Analysis/ComData/mclserp_data.csv") %>%
  select(-X) %>%
   rename(species.name = Species_Name)

jasper_data <- read.csv("Analysis/ComData/jasper_data.csv")

swan_data <- read.csv("Analysis/ComData/swanton_data.csv")

angelo_data <- read.csv("Analysis/ComData/angelo_data.csv") %>%
  select(-X)  %>%
  mutate(site = "Angelo")

McLAnn_data <- read.csv("Analysis/ComData/mclann_data.csv") %>%
   rename(species.name = Species_Name)

car_data <- read.csv("Analysis/ComData/carrizo_data.csv") %>%
    rename(species.name = Species.Name)

ucsc_data <- read.csv("Analysis/ComData/ucsc_data.csv")
```

```{r Post-import tidying and relative cover data}
## angelo
rel_ang_data <- angelo_data %>%
  select(year, plot, species.name, cover) %>%
  group_by(plot, year) %>%
  mutate(sumcov = sum(cover),
         relcov = cover/sumcov)

## carrizo
car_data <- car_data %>%
  select(-X) %>%
  filter(species.name != "litter",
         species.name != "bare",
         species.name != "hole",
         species.name != "moss") %>%
  mutate(site = "Carrizo")
rel_car_data <- car_data %>%
  select(year, Plot, species.name, Intercepts) %>%
  distinct(year, Plot, species.name, .keep_all = TRUE) %>%
  group_by(Plot, year) %>%
  mutate(sumintercept = sum(Intercepts),
         relcov = Intercepts/sumintercept)

## elkhorn
elkhorn_data <- elkhorn_data %>%
  filter(species.name != "Moss",
         species.name != "Thatch",
         species.name != "Bare ground") %>%
  mutate(site = "Elkhorn")
rel_elkhorn_data <- elkhorn_data %>%
  select(year, rep, species.name, intercepts) %>%
  group_by(rep, year) %>%
  mutate(sumintercept = sum(intercepts),
         relcov = intercepts/sumintercept)

## mcL serp
mcLserp_data <- mcLserp_data %>%
  filter(species.name != "Bare",
         species.name != "Rock",
         species.name != "Unknown forb") %>%
  mutate(site = "McL Serp",
         year = Year)
rel_mcLserp <- mcLserp_data %>%
  group_by(Site, Year, plot, species.name) %>%
  summarise(Cover = sum(Cover)) %>%
  ungroup() %>%
  group_by(plot, Year) %>%
  mutate(sumcov = sum(Cover),
         relcov = Cover/sumcov)

## mcL ann
McLAnn_data <- McLAnn_data %>%
  select(-X) %>%
  filter(species.name != "Bare",
         species.name != "Rock",
         species.name != "Unknown grass",
         species.name != "Unknown forb") %>%
  mutate(site = "McL Ann",
         year = Year)
rel_McLAnn <- McLAnn_data %>%
  group_by(Site, Year, plot, species.name) %>%
  summarise(Cover = sum(Cover)) %>%
  ungroup() %>%
  group_by(plot, Year) %>%
  mutate(sumcov = sum(Cover),
         relcov = Cover/sumcov)

## jasper
jasper_data <- jasper_data %>%
  select(-X) %>%
  filter(cover > 0) %>%
  group_by(uniqueID, year) %>%
  mutate(sumcov = sum(cover),
         relcov = cover/sumcov) %>%
  mutate(site = "Jasper")

## swanton
swan_data <- swan_data %>%
  select(-X) %>%
  filter(species.name != "Moss",
         species.name != "Thatch",
         species.name != "Bare ground") %>%
  mutate(site = "Swanton")
rel_swan_data <- swan_data %>%
  select(year, rep, species.name, intercepts) %>%
  group_by(rep, year) %>%
  mutate(sumintercept = sum(intercepts),
         relcov = intercepts/sumintercept)

## ucsc
ucsc_data <- ucsc_data %>%
  select(-X) %>%
  filter(species.name != "Thatch",
         species.name != "Bare ground") %>%
  mutate(site = "UCSC")
rel_ucsc_data <- ucsc_data %>%
  select(year, rep, species.name, intercepts) %>%
  group_by(rep, year) %>%
  mutate(sumintercept = sum(intercepts),
         relcov = intercepts/sumintercept)
```



```{r prism data import and prep, echo = FALSE}
weather <- read.csv("PRISM_data.csv") %>%
  select(-X)

wtryr_weather <- read.csv("PRISM_wtryr_data.csv") %>%
  select(-X)

```

# Changes in guild-level cover over time

```{r converting species level cover to guild level cover}
ang_gcover <- angelo_data %>%
  group_by(year, plot, guild) %>%
  summarise(cover = sum(cover)) %>% ungroup() %>%
  group_by(year, plot) %>%
  mutate(sumcov = sum(cover),
         relcov = cover/sumcov) %>% select(plot, year, relcov, guild)  %>%
  spread(guild, relcov) %>%
  replace(is.na(.), 0) %>%
  add_column(NAG = 0) %>% add_column(NAGr = 0) %>% add_column(EPG = 0) %>%
  add_column(NPGr = 0) %>% add_column(NPS = 0) %>% add_column(NPT = 0) %>%
  mutate(Nat = (NAF+NAG+NAGr+NPF+NPG+NPGr+NPS+NPT),
         Exo = (EAF+EAG+EPF+EPG),
         NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT)) %>%
  ungroup() %>% 
  gather('Nat', 'Exo', 'NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', key = "guild", value = "relcov") %>%
  group_by(year, guild) %>%
  summarise(meancov = mean(relcov),
            secov = (std.error(relcov))) %>%
  mutate(site = "Angelo")

car_gcover <- car_data %>%
  group_by(year, Plot, guild) %>%
  summarise(cover = sum(Intercepts)) %>% ungroup() %>%
  group_by(year, Plot) %>%
  mutate(sumcov = sum(cover),
         relcov = cover/sumcov) %>% select(Plot, year, relcov, guild)  %>%
  spread(guild, relcov) %>%
  replace(is.na(.), 0) %>%
  add_column(NAGr = 0) %>% add_column(EPG = 0) %>% add_column(NPGr = 0) %>%
  add_column(NPS = 0) %>% add_column(NPT = 0) %>%
  mutate(Nat = (NAF+NAG+NAGr+NPF+NPG+NPGr+NPS+NPT),
         Exo = (EAF+EAG+EPF+EPG),
         NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT)) %>%
  ungroup() %>% 
  gather('Nat', 'Exo', 'NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', key = "guild", value = "relcov") %>%
  group_by(year, guild) %>%
  summarise(meancov = mean(relcov),
            secov = (std.error(relcov))) %>%
  mutate(site = "Carrizo")

elk_gcover <- elkhorn_data %>%
  group_by(year, rep, guild) %>%
  summarise(cover = sum(intercepts)) %>% ungroup() %>%
  group_by(year, rep) %>%
  mutate(sumcov = sum(cover),
         relcov = cover/sumcov) %>% select(rep, year, relcov, guild)  %>%
  spread(guild, relcov) %>%
  replace(is.na(.), 0) %>%
  add_column(NAF = 0) %>% add_column(NAG = 0) %>% add_column(NPS = 0) %>% add_column(NPT = 0) %>%
  mutate(Nat = (NAF+NAG+NAGr+NPF+NPG+NPGr+NPS+NPT),
         Exo = (EAF+EAG+EPF+EPG),
         NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT)) %>%
  ungroup() %>% 
  gather('Nat', 'Exo', 'NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', key = "guild", value = "relcov") %>%
  group_by(year, guild) %>%
  summarise(meancov = mean(relcov),
            secov = (std.error(relcov))) %>%
  mutate(site = "Elkhorn")

jasp_gcover <- jasper_data %>%
  group_by(year, uniqueID, guild) %>%
  summarise(cover = sum(cover)) %>% ungroup() %>%
  group_by(year, uniqueID) %>%
  mutate(sumcov = sum(cover),
         relcov = cover/sumcov) %>% select(uniqueID, year, relcov, guild)  %>%
  spread(guild, relcov) %>%
  replace(is.na(.), 0) %>% 
  add_column(NAGr = 0) %>%  add_column(EAF = 0) %>% add_column(EPF = 0) %>%
  add_column(EPG = 0) %>%  add_column(NPGr = 0) %>% add_column(NPS = 0) %>%
  add_column(NPT = 0) %>%
  mutate(Nat = (NAF+NAG+NAGr+NPF+NPG+NPGr+NPS+NPT),
         Exo = (EAF+EAG+EPF+EPG),
         NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT)) %>%
  ungroup() %>% 
  gather('Nat', 'Exo', 'NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', key = "guild", value = "relcov") %>%
  group_by(year, guild) %>%
  summarise(meancov = mean(relcov),
            secov = (std.error(relcov))) %>%
  mutate(site = "Jasper")

McLAnn_gcover <- McLAnn_data %>%
  filter(Cover > 0) %>%
  group_by(year, plot, guild) %>%
  summarise(cover = sum(Cover)) %>% ungroup() %>%
  group_by(year, plot) %>%
  mutate(sumcov = sum(cover),
         relcov = cover/sumcov) %>% select(plot, year, relcov, guild)  %>%
  spread(guild, relcov) %>%
  replace(is.na(.), 0) %>%
  add_column(NAGr = 0) %>% add_column(NPGr = 0) %>% 
  mutate(Nat = (NAF+NAG+NAGr+NPF+NPG+NPGr+NPS+NPT),
         Exo = (EAF+EAG+EPF+EPG),
         NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT)) %>%
  ungroup() %>% 
  gather('Nat', 'Exo', 'NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', key = "guild", value = "relcov") %>%
  group_by(year, guild) %>%
  summarise(meancov = mean(relcov),
            secov = (std.error(relcov))) %>%
  mutate(site = "McL Ann")

mcLserp_gcover <- mcLserp_data %>%
  filter(Cover > 0) %>%
  group_by(year, plot, guild) %>%
  summarise(cover = sum(Cover)) %>% ungroup() %>%
  group_by(year, plot) %>%
  mutate(sumcov = sum(cover),
         relcov = cover/sumcov) %>% select(plot, year, relcov, guild)  %>%
  spread(guild, relcov) %>%
  replace(is.na(.), 0) %>%
  add_column(NAGr = 0) %>% add_column(NPGr = 0) %>% add_column(EPG = 0) %>% 
  mutate(Nat = (NAF+NAG+NAGr+NPF+NPG+NPGr+NPS+NPT),
         Exo = (EAF+EAG+EPF+EPG),
         NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT)) %>%
  ungroup() %>% 
  gather('Nat', 'Exo', 'NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', key = "guild", value = "relcov") %>%
  group_by(year, guild) %>%
  summarise(meancov = mean(relcov),
            secov = (std.error(relcov))) %>%
  mutate(site = "McL Serp")

swan_gcover <- swan_data %>%
  group_by(year, rep, guild) %>%
  summarise(cover = sum(intercepts)) %>% ungroup() %>%
  group_by(year, rep) %>%
  mutate(sumcov = sum(cover),
         relcov = cover/sumcov) %>% select(rep, year, relcov, guild)  %>%
  spread(guild, relcov) %>%
  replace(is.na(.), 0) %>%
  add_column(NAF = 0) %>% add_column(NAG = 0) %>% add_column(EPG = 0) %>% 
  add_column(NPGr = 0) %>% add_column(NPS = 0) %>% add_column(NPT = 0) %>%
  mutate(Nat = (NAF+NAG+NAGr+NPF+NPG+NPGr+NPS+NPT),
         Exo = (EAF+EAG+EPF+EPG),
         NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT)) %>%
  ungroup() %>% 
  gather('Nat', 'Exo', 'NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', key = "guild", value = "relcov") %>%
  group_by(year, guild) %>%
  summarise(meancov = mean(relcov),
            secov = (std.error(relcov))) %>%
  mutate(site = "Swanton")

ucsc_gcover <- ucsc_data %>%
  group_by(year, rep, guild) %>%
  summarise(cover = sum(intercepts)) %>% ungroup() %>%
  group_by(year, rep) %>%
  mutate(sumcov = sum(cover),
         relcov = cover/sumcov) %>% select(rep, year, relcov, guild)  %>%
  spread(guild, relcov) %>%
  replace(is.na(.), 0) %>%
  add_column(NAF = 0) %>% add_column(NAG = 0) %>% add_column(NPS = 0) %>% add_column(NPT = 0) %>%
  mutate(Nat = (NAF+NAG+NAGr+NPF+NPG+NPGr+NPS+NPT),
         Exo = (EAF+EAG+EPF+EPG),
         NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT)) %>%
  ungroup() %>% 
  gather('Nat', 'Exo', 'NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', key = "guild", value = "relcov") %>%
  group_by(year, guild) %>%
  summarise(meancov = mean(relcov),
            secov = (std.error(relcov))) %>%
  mutate(site = "UCSC")

all.gcov <- full_join(mcLserp_gcover, swan_gcover)
all.gcov <- full_join(all.gcov, elk_gcover)
all.gcov <- full_join(all.gcov, jasp_gcover)
all.gcov <- full_join(all.gcov, ang_gcover)
all.gcov <- full_join(all.gcov, McLAnn_gcover)
all.gcov <- full_join(all.gcov, car_gcover)
all.gcov <- full_join(all.gcov, ucsc_gcover)

all_gcov <- left_join(all.gcov, wtryr_weather, by = c("year", "site")) 

all_gcov_means <- all_gcov %>%
  group_by(site, guild, year) %>%
  summarise(serelcov = std.error(meancov),
            meanrelcov = mean(meancov),
            precip = mean(precip),
            tmean = mean(tmean),
            tmax = mean(tmax),
            tmin = mean(tmin))
  

```


```{r tidy gcover workspace, include=FALSE}
remove(mcLserp_gcover, swan_gcover, elk_gcover, jasp_gcover, ang_gcover, McLAnn_gcover, car_gcover, ucsc_gcover)
```

```{r guild cover graphs}
ggplot(all_gcov_means, aes(x = year, y = meanrelcov, color = site)) +
  geom_line() +
  labs(title = "",
       x = "Year",
       y = "Relative cover") +
  facet_grid(~guild) 

exo.gcov <- all_gcov_means %>% filter(guild == "Exo")
nat.gcov <- all_gcov_means %>% filter(guild == "Nat")

grid.arrange(
  ggplot(nat.gcov, aes(x = year, y = meanrelcov, color = site)) +
  geom_point() +
    geom_line() +
  labs(title = "",
       x = "Year",
       y = "Relative cover"),
  ggplot(exo.gcov, aes(x = year, y = meanrelcov, color = site)) +
  geom_point() +
    geom_line() +
  labs(title = "",
       x = "Year",
       y = "Relative cover"))

```


# Species richness over time

```{r richness by guild, echo = FALSE}

ang_grich_means <- angelo_data %>%
  group_by(year, plot, guild) %>%
  summarise(rich = n_distinct(species.name)) %>%
  spread(guild, rich) %>%
  replace(is.na(.), 0) %>%
  add_column(NAG = 0) %>% add_column(NAGr = 0) %>% add_column(EPG = 0) %>%
  add_column(NPGr = 0) %>% add_column(NPS = 0) %>% add_column(NPT = 0) %>%
  mutate(NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT)) %>%
  ungroup() %>% 
  gather('NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', key = "guild", value = "rich") %>%
  group_by(year, guild) %>%
  summarise(meanrich = mean(rich),
            serich = (std.error(rich))) %>%
  mutate(site = "Angelo")

car_grich_means <- car_data %>%
  group_by(year, Plot, guild) %>%
  summarise(rich = n_distinct(species.name)) %>%
  spread(guild, rich) %>%
  replace(is.na(.), 0) %>%
  add_column(NAGr = 0) %>% add_column(EPG = 0) %>% add_column(NPGr = 0) %>%
  add_column(NPS = 0) %>% add_column(NPT = 0) %>%
  mutate(NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT)) %>%
  ungroup() %>% 
  gather('NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', key = "guild", value = "rich") %>%
  group_by(year, guild) %>%
  summarise(meanrich = mean(rich),
            serich = (std.error(rich))) %>%
  mutate(site = "Carrizo")

elk_grich_means <- elkhorn_data %>%
  group_by(year, rep, guild) %>%
  summarise(rich = n_distinct(species.name)) %>%
  spread(guild, rich) %>%
  replace(is.na(.), 0) %>%
  add_column(NAF = 0) %>% add_column(NAG = 0) %>% add_column(NPS = 0) %>% add_column(NPT = 0) %>%
  mutate(NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT)) %>%
  ungroup() %>% 
  gather('NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', key = "guild", value = "rich") %>%
  group_by(year, guild) %>%
  summarise(meanrich = mean(rich),
            serich = (std.error(rich))) %>%
  mutate(site = "Elkhorn")

jasp_grich_means <- jasper_data %>%
  group_by(year, uniqueID, guild) %>%
  summarise(rich = n_distinct(species.name)) %>%  spread(guild, rich) %>%
  replace(is.na(.), 0) %>% 
  add_column(NAGr = 0) %>%  add_column(EAF = 0) %>% add_column(EPF = 0) %>%
  add_column(EPG = 0) %>%  add_column(NPGr = 0) %>% add_column(NPS = 0) %>%
  add_column(NPT = 0) %>%
  mutate(NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT)) %>%
  ungroup() %>% 
  gather('NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', key = "guild", value = "rich") %>%
  group_by(year, guild) %>%
  summarise(meanrich = mean(rich),
            serich = (std.error(rich))) %>%
  mutate(site = "Jasper")

McLAnn_grich_means <- McLAnn_data %>%
  group_by(year, plot, guild) %>%
  summarise(rich = n_distinct(species.name)) %>%  spread(guild, rich) %>%
  replace(is.na(.), 0) %>%
  add_column(NAGr = 0) %>% add_column(NPGr = 0) %>% 
  mutate(NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT)) %>%
  ungroup() %>% 
  gather('NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', key = "guild", value = "rich") %>%
  group_by(year, guild) %>%
  summarise(meanrich = mean(rich),
            serich = (std.error(rich))) %>%
  mutate(site = "McL Ann")

mcLserp_grich_means <- mcLserp_data %>%
  group_by(year, plot, guild) %>%
  summarise(rich = n_distinct(species.name)) %>%  spread(guild, rich) %>%
  replace(is.na(.), 0) %>%
  add_column(NAGr = 0) %>% add_column(NPGr = 0) %>% 
  mutate(NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT)) %>%
  ungroup() %>% 
  gather('NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', key = "guild", value = "rich") %>%
  group_by(year, guild) %>%
  summarise(meanrich = mean(rich),
            serich = (std.error(rich))) %>%
  mutate(site = "McL Serp")

swan_grich_means <- swan_data %>%
  group_by(year, rep, guild) %>%
  summarise(rich = n_distinct(species.name)) %>%
  spread(guild, rich) %>%
  replace(is.na(.), 0) %>%
  add_column(NAF = 0) %>% add_column(NAG = 0) %>% add_column(EPG = 0) %>% 
  add_column(NPGr = 0) %>% add_column(NPS = 0) %>% add_column(NPT = 0) %>%
  mutate(NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT)) %>%
  ungroup() %>% 
  gather('NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', key = "guild", value = "rich") %>%
  group_by(year, guild) %>%
  summarise(meanrich = mean(rich),
            serich = (std.error(rich))) %>%
  mutate(site = "Swanton")

ucsc_grich_means <- ucsc_data %>%
  group_by(year, rep, guild) %>%
  summarise(rich = n_distinct(species.name)) %>%
  spread(guild, rich) %>%
  replace(is.na(.), 0) %>%
  add_column(NAF = 0) %>% add_column(NAG = 0) %>% add_column(NPS = 0) %>% add_column(NPT = 0) %>%
  mutate(NatAnns = (NAF+NAG+NAGr),
         ExoAnns = (EAF+EAG),
         ExoPers = (EPF+EPG),
         NatPers = (NPF+NPG+NPGr+NPS+NPT)) %>%
  ungroup() %>% 
  gather('NatAnns', 'ExoAnns', 'ExoPers', 'NatPers', key = "guild", value = "rich") %>%
  group_by(year, guild) %>%
  summarise(meanrich = mean(rich),
            serich = (std.error(rich))) %>%
  mutate(site = "UCSC")


all.grich <- full_join(mcLserp_grich_means, swan_grich_means)
all.grich <- full_join(all.grich, elk_grich_means)
all.grich <- full_join(all.grich, jasp_grich_means)
all.grich <- full_join(all.grich, ang_grich_means)
all.grich <- full_join(all.grich, McLAnn_grich_means)
all.grich <- full_join(all.grich, car_grich_means)
all.grich <- full_join(all.grich, ucsc_grich_means)

all_grich_weather <- left_join(all.grich, wtryr_weather, by = c("year", "site")) 


all_grich_means <- all_grich_weather %>%
  group_by(site, guild, year) %>%
  summarise(serich = std.error(meanrich),
            meanrich = mean(meanrich),
            precip = mean(precip),
            tmean = mean(tmean),
            tmax = mean(tmax),
            tmin = mean(tmin))
  
ggplot(all_grich_means, aes(x = year, y = meanrich, color = site)) +
  geom_line() +
  labs(title = "All sites - Richness change",
       x = "Year",
       y = "Richness (# spp.)") +
  facet_grid(~guild)

```


```{r richness, echo = FALSE}

elk_rich_means <- elkhorn_data %>%
  group_by(year, rep) %>%
  summarise(rich = n_distinct(species.name)) %>%
  ungroup() %>% group_by(year) %>%
  summarise(meanrich = mean(rich),
            serich = (std.error(rich))) %>%
  mutate(site = "Elkhorn")

jasp_rich_means <- jasper_data %>%
  group_by(year, uniqueID) %>%
  summarise(rich = n_distinct(species.name)) %>%
  ungroup() %>% group_by(year) %>%
  summarise(meanrich = mean(rich),
            serich = (std.error(rich))) %>%
  mutate(site = "Jasper")

swan_rich_means <- swan_data %>%
  group_by(year, rep) %>%
  summarise(rich = n_distinct(species.name)) %>%
  ungroup() %>% group_by(year) %>%
  summarise(meanrich = mean(rich),
            serich = (std.error(rich))) %>%
  mutate(site = "Swanton")

mcLserp_rich_means <- mcLserp_byquad %>%
  group_by(Year, plot) %>%
  summarise(rich = n_distinct(species.name)) %>%
  ungroup() %>% group_by(Year) %>%
  summarise(meanrich = mean(rich),
            serich = (std.error(rich))) %>%
  mutate(site = "McL Serp",
         year = Year)

McLAnn_rich_means <- McLAnn_byquad %>%
  group_by(Year, plot) %>%
  summarise(rich = n_distinct(species.name)) %>%
  ungroup() %>% group_by(Year) %>%
  summarise(meanrich = mean(rich),
            serich = (std.error(rich))) %>%
  mutate(site = "McL Ann",
         year = Year)

ang_rich_means <- angelo_data %>%
  group_by(year, plot) %>%
  summarise(rich = n_distinct(species.name)) %>%
  ungroup() %>% group_by(year) %>%
  summarise(meanrich = mean(rich),
            serich = (std.error(rich))) %>%
  mutate(site = "Angelo")

car_rich_means <- car_data_rel %>%
  group_by(year, Plot) %>%
  summarise(rich = n_distinct(species.name)) %>%
  ungroup() %>% group_by(year) %>%
  summarise(meanrich = mean(rich),
            serich = (std.error(rich))) %>%
  mutate(site = "Carrizo")

ucsc_rich_means <- ucsc_data %>%
  group_by(year, rep) %>%
  summarise(rich = n_distinct(species.name)) %>%
  ungroup() %>% group_by(year) %>%
  summarise(meanrich = mean(rich),
            serich = (std.error(rich))) %>%
  mutate(site = "UCSC")


all.rich <- full_join(mcLserp_rich_means, swan_rich_means)
all.rich <- full_join(all.rich, elk_rich_means)
all.rich <- full_join(all.rich, jasp_rich_means)
all.rich <- full_join(all.rich, ang_rich_means)
all.rich <- full_join(all.rich, McLAnn_rich_means)
all.rich <- full_join(all.rich, car_rich_means)
all.rich <- full_join(all.rich, ucsc_rich_means)

all.rich <- all.rich %>%
  select(-Year)

all_rich_weather <- left_join(all.rich, wtryr_weather, by = c("year", "site"))

all_rich_means <- all_rich_weather %>%
  group_by(site) %>%
  summarise(serich = std.error(meanrich),
            meanrich = mean(meanrich),
            precip = mean(precip),
            tmean = mean(tmean),
            tmax = mean(tmax),
            tmin = mean(tmin))
  
ggplot(all.rich, aes(x = year, y = meanrich, color = site)) +
  geom_line() +
  geom_errorbar(aes(ymin = meanrich-serich, ymax = meanrich+serich)) +
  labs(title = "All sites - Richness change",
       x = "Year",
       y = "Richness (# spp.)")

ggplot(all_rich_means, aes(x = precip, y = meanrich, color = site)) +
  geom_point() +
  geom_errorbar(aes(ymin = meanrich-serich, ymax = meanrich+serich)) +
  labs(title = "All sites - Richness change",
       x = "Precipitation",
       y = "Richness (# spp.)")

ggplot(all.rich, aes(x = year, y = meanrich, color = site)) +
  geom_point() +
      labs(title = "All sites - Species Richness over time",
       x = "Year",
       y = "Species Richness") +
  geom_errorbar(aes(ymin = meanrich-serich, ymax = meanrich+serich)) +
  facet_wrap(~site, ncol = 2, scales = "free") +
  theme(legend.position = "none")

```


```{r richness per area, eval = FALSE}
elk_richarea <- elkhorn_data %>% 
  mutate(plot.size = 4) %>% group_by(year) %>%
  mutate(no.plots = n_distinct(rep),
         area = no.plots*plot.size) %>%
  group_by(year, area, site) %>%
  summarise(rich = n_distinct(species.name)) %>%
  mutate(richarea = rich/area)
# note that Elkhorn doesn't have any datapoints in 2001. 

mcLserp_richarea <- mcLserp_data %>%
  mutate(plot.size = 1) %>% group_by(year) %>%
  mutate(no.plots = n_distinct(plot)) %>% 
  mutate(area = no.plots*plot.size) %>%
  group_by(year, area, site) %>%
  summarise(rich = n_distinct(species.name)) %>%
  mutate(richarea = rich/area)

jasp_richarea <- jasper_data %>%
  mutate(plot.size = 1) %>% group_by(year) %>%
  mutate(no.plots = n_distinct(uniqueID),
         area = no.plots*plot.size) %>%
  group_by(year, area, site) %>%
  summarise(rich = n_distinct(species.name)) %>%
  mutate(richarea = rich/area)

swan_richarea <- swan_data %>%
  mutate(plot.size = 4) %>% group_by(year) %>%
  mutate(no.plots = n_distinct(rep),
         area = no.plots*plot.size) %>%
  group_by(year, area, site) %>%
  summarise(rich = n_distinct(species.name)) %>%
  mutate(richarea = rich/area)

angelo_richarea <- angelo_data %>%
  mutate(plot.size = 2.5) %>% group_by(year) %>%
  mutate(no.plots = n_distinct(plot),
         area = no.plots*plot.size) %>%
  group_by(year, area, site) %>%
  summarise(rich = n_distinct(species.name)) %>%
  mutate(richarea = rich/area)
  
McLAnn_richarea <- McLAnn_data %>%
    mutate(plot.size = 1) %>% group_by(year) %>%
  mutate(no.plots = n_distinct(plot),
         area = no.plots*plot.size) %>%
  group_by(year, area, site) %>%
  summarise(rich = n_distinct(species.name)) %>%
  mutate(richarea = rich/area)
  
car_richarea <- car_data %>%
  mutate(plot.size = 1) %>% group_by(year) %>%
  mutate(no.plots = n_distinct(Plot),
         area = no.plots*plot.size) %>%
  group_by(year, area, site) %>%
  summarise(rich = n_distinct(species.name)) %>%
  mutate(richarea = rich/area)
  
ucsc_richarea <- ucsc_data %>%
  mutate(plot.size = 4) %>% group_by(year) %>%
  mutate(no.plots = n_distinct(rep),
         area = no.plots*plot.size) %>%
  group_by(year, area, site) %>%
  summarise(rich = n_distinct(species.name)) %>%
  mutate(richarea = rich/area)

all.richarea <- full_join(angelo_richarea, car_richarea)
all.richarea <- full_join(all.richarea, elk_richarea)
all.richarea <- full_join(all.richarea, jasp_richarea)
all.richarea <- full_join(all.richarea, McLAnn_richarea)
all.richarea <- full_join(all.richarea, mcLserp_richarea)
all.richarea <- full_join(all.richarea, swan_richarea)
all.richarea <- full_join(all.richarea, ucsc_richarea)

remove(angelo_richarea, car_richarea, elk_richarea, jasp_richarea, McLAnn_richarea, mcLserp_richarea, swan_richarea, ucsc_richarea)


all.richarea.weather <- left_join(all.richarea, wtryr_weather, by = c("year", "site"))

all.richarea.means <- all.richarea.weather %>%
  group_by(site) %>%
  summarise(serich = std.error(richarea),
            meanrich = mean(richarea),
            precip = mean(precip),
            tmean = mean(tmean),
            tmax = mean(tmax),
            tmin = mean(tmin))


ggplot(all.richarea.means, aes(x = precip, y = meanrich, color = site)) +
  geom_line() +
  geom_errorbar(aes(ymin = meanrich-serich, ymax = meanrich+serich)) +
  labs(title = "",
       x = "Precipitation",
       y = "Richness (# spp/m^2)")

```


# Grouped Turnover Graph

```{r turnover, echo=FALSE}
## missing Carrizo because that data isn't taken in the same plots every year

ang_turnover <- turnover(df = ang_data_rel,
                          time.var = "year",
                          species.var = "species.name",
                          abundance.var = "relcov",
                          replicate.var = "plot") %>%
  mutate(site = "Angelo")

elk_turnover <- turnover(df = elkhorn_data_rel,
                          time.var = "year",
                          species.var = "species.name",
                          abundance.var = "relcov",
                          replicate.var = "plot") %>%
  mutate(site = "Elkhorn") 

ucsc_turnover <- turnover(df = ucsc_data_rel,
                          time.var = "year",
                          species.var = "species.name",
                          abundance.var = "relcov",
                          replicate.var = "plot") %>%
  mutate(site = "UCSC")

swan_turnover <- turnover(df = swan_data_rel,
                          time.var = "year",
                          species.var = "species.name",
                          abundance.var = "relcov",
                          replicate.var = "plot") %>%
  mutate(site = "Swanton") 

jasp_turnover <- turnover(df = jasper_data,
                          time.var = "year",
                          species.var = "species.name",
                          abundance.var = "relcov",
                          replicate.var = "plot") %>%
  mutate(site = "Jasper") 

McLAnn_turnover <- turnover(df = McLAnn_byquad,
                          time.var = "year",
                          species.var = "species.name",
                          abundance.var = "relcov",
                          replicate.var = "plot") %>%
  mutate(site = "McL Ann")

mcLserp_turnover <- turnover(df = mcLserp_byquad,
                          time.var = "year",
                          species.var = "species.name",
                          abundance.var = "relcov",
                          replicate.var = "plot") %>%
  mutate(site = "McL Serp")

all_turnover <- full_join(ang_turnover, elk_turnover)
all_turnover <- full_join(all_turnover, ucsc_turnover)
all_turnover <- full_join(all_turnover, swan_turnover)
all_turnover <- full_join(all_turnover, jasp_turnover)
all_turnover <- full_join(all_turnover, mcLserp_turnover)
all_turnover <- full_join(all_turnover, McLAnn_turnover)

all_turnover <- all_turnover %>%
  rename(turnover = total) 

all_turn_weather <- left_join(all_turnover, wtryr_weather, by = c("year", "site"))

all_turn_means <- all_turn_weather %>%
  group_by(site) %>%
  summarise(meanturn = mean(turnover),
            seturn = std.error(turnover),
            precip = mean(precip),
            tmean = mean(tmean),
            tmax = mean(tmax),
            tmin = mean(tmin))

```

```{r turnover graphs, echo = FALSE}
ggplot(all_turn_weather, aes(x = year, y = turnover, color = site)) +
  geom_point() +
  labs(title = "All sites - Community Turnover",
       x = "Year",
       y = "Turnover (# spp. lost+gained / total # spp.)") + stat_smooth(method = "lm", se = F, size =  1)

graph_turn <- ggplot(all_turn_means, aes(x = site, y = meanturn, color = site)) +
  geom_point() +
  geom_errorbar(aes(ymin = meanturn-seturn, ymax = meanturn+seturn)) +
  labs(title = "Community turnover by site",
     x = "Mean water-year precipitation (mm) during study years",
     y = "Turnover)") +
  theme_classic() +
  theme(legend.position = "none") +
  stat_smooth(method = "lm", se = F, size =  1)

graph_precip_turn <- ggplot(all_turn_means, aes(x = precip, y = meanturn, color = site)) +
  geom_point() +
  geom_errorbar(aes(ymin = meanturn-seturn, ymax = meanturn+seturn)) +
  labs(title = "Community turnover by water year precip",
     x = "Mean water-year precipitation (mm) during study years",
     y = "Turnover)") +
  theme_classic() +
  theme(legend.position = "none") +
  stat_smooth(method = "lm", se = F, size =  1)

graph_temp_turn <- ggplot(all_turn_means, aes(x = tmin, y = meanturn, color = site)) +
  geom_point() +
  geom_errorbar(aes(ymin = meanturn-seturn, ymax = meanturn+seturn)) +
  labs(title = "Community turnover by min. temp",
     x = "Minimum annual temperature during study years",
     y = "Turnover") + 
  theme_classic() +
  theme(legend.position = "bottom") +
  stat_smooth(method = "lm", se = F, size =  1)

turn_leg <- g_legend(temp_turn)

grid.arrange(graph_turn, 
             graph_precip_turn,
             graph_temp_turn + theme(legend.position = "none"), 
             turn_leg, 
             nrow = 4)

# ggplot(turnover_means, aes(x = year, y = meanturn, color = Site)) +
#  geom_line() +
#  geom_errorbar(aes(ymin = meanturn-seturn, ymax = meanturn+seturn)) +
#  labs(title = "All sites - Community Turnover",
#       x = "Year",
#       y = "Turnover (# spp. lost+gained / total # spp.)") + stat_smooth(method = "lm", se = F, size =  1)

# ggplot(turnover_means, aes(x = year, y = meanturn, color = Site)) +
#  geom_line() +
#  geom_errorbar(aes(ymin = meanturn-seturn, ymax = meanturn+seturn)) +
#  labs(title = "All sites - Community Turnover",
#       x = "Year",
#       y = "Turnover (# spp. lost+gained / total # spp.)")
```



# CTI

```{r old code storage, eval=FALSE}
all.CTI <- read.csv("allsites_CTI.csv")


ggplot(all.CTI, aes(x=year, y=meanCTI, color = site)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymin = meanCTI-seCTI, ymax = meanCTI+seCTI), width=0.2) +
    labs(title = "All sites - Community Temperature Index over time",
       x = "Year",
       y = "Community Temperature Index") +
  stat_smooth(method = "lm", se = F, size =  1)

ggplot(all.CTI, aes(x=year, y=meanCTI, color = site)) +
  geom_point() +
  geom_errorbar(aes(ymin = meanCTI-seCTI, ymax = meanCTI+seCTI), width=0.2) +
      labs(title = "All sites - Community Temperature Index over time",
       x = "Year",
       y = "Community Temperature Index") +
  facet_wrap(~site, ncol = 2, scales = "free") +
  theme(legend.position = "none") +
  stat_smooth(method = "lm", se = F, size =  1)

ggplot(all.CTI, aes(x=year, y=meanCPI, color = site)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymin = meanCPI-seCPI, ymax = meanCPI+seCPI), width=0.2) +
      labs(title = "All sites - Community Precipitation Index over time",
       x = "Year",
       y = "Community Precipitation Index") +
  stat_smooth(method = "lm", se = F, size =  1)

ggplot(all.CTI, aes(x=year, y=meanCPI, color = site)) +
  geom_point() +
      labs(title = "All sites - Community Precipitation Index over time",
       x = "Year",
       y = "Community Precipitation Index") +
  geom_errorbar(aes(ymin = meanCPI-seCPI, ymax = meanCPI+seCPI), width=0.2) +
  facet_wrap(~site, ncol = 2, scales = "free") +
  theme(legend.position = "none") +
  stat_smooth(method = "lm", se = F, size =  1)

# code for adding a flat line
#  stat_smooth(method = "lm", se = F, size =  1)

```

```{r CTI import and prep}
setwd("CTI Data")
ang_cti <- read.csv("Angelo_CTI.csv")
car_cti <- read.csv("Carrizo_CTI.csv") %>%
  rename(site = Site)
elk_cti <- read.csv("Elkhorn_CTI.csv") %>%
  rename(site = Site)
jasp_cti <- read.csv("Jasper_CTI.csv") %>%
  rename(site = Site)
McLAnn_cti <- read.csv("McLAnn_CTI.csv")  %>%
  rename(site = Site)
mcLserp_cti <- read.csv("McLSerp_CTI.csv") %>%
  rename(site = Site)
Swan_cti <- read.csv("Swanton_CTI.csv")  %>%
  rename(site = Site)
UCSC_cti <- read.csv("UCSC_CTI.csv")  %>%
  rename(site = Site)

all.CTI <- full_join(ang_cti, car_cti)
all.CTI <- full_join(all.CTI, elk_cti)
all.CTI <- full_join(all.CTI, jasp_cti)
all.CTI <- full_join(all.CTI, McLAnn_cti)
all.CTI <- full_join(all.CTI, mcLserp_cti)
all.CTI <- full_join(all.CTI, Swan_cti)
all.CTI <- full_join(all.CTI, UCSC_cti)

all.CTI <- all.CTI %>%
  select(-X, -hotTI, -ColdTI)

all.CTI <- left_join(all.CTI, wtryr_weather, by = c("year", "site")) %>%
  filter(year >= 1999)
```

```{r cti graph}
ggplot(all.CTI, aes(x=year, y=CTI)) +
  geom_boxplot(aes(group = year)) +
      labs(title = "All sites - Community Temperature Index over time",
       x = "Year",
       y = "Community Temperature Index") +
  facet_wrap(~site, nrow=2) 

ggplot(all.CTI, aes(x=year, y=CTI)) +
  geom_boxplot(aes(group = year)) +
      labs(title = "All sites - Community Temperature Index over time",
       x = "Year",
       y = "Community Temperature Index") +
  stat_smooth(method = "lm", se = F, size =  1)
  

ggplot(all.CTI, aes(x=year, y=CPI)) +
  geom_boxplot(aes(group = year)) +
      labs(title = "All sites - Community Precipitation Index over time",
       x = "Year",
       y = "Community Precipitation Index") +
  facet_wrap(~site, nrow=2) 
```


## Analysis of CTI

In our CTI model, we expect the following:  
* Response variables (one at a time)
+ CTI
+ CPI

* Fixed Effects
+ Time/Year
+ Climate factors?

* Random Effects
+ Site
+ Plot within site



```{r explore CTI}
hist(all.CTI$CTI)

cti.lm.ang <- nlme::lme(CTI ~ year + precip + tmin,
                    data = all.CTI[all.CTI$site == "Angelo",], method = "REML",
                    random =  ~ 1 | site/plot,
                    # correlation=corCAR1(form=~cYear|Site)
)

summary(cti.lm.ang)

cti.lm.ang <- nlme::lme(CTI ~ precip + tmin,
                    data = all.CTI[all.CTI$site == "Angelo",], method = "REML",
                    random =  ~ 1 | site/plot,
                    # correlation=corCAR1(form=~cYear|Site)
)

summary(cti.lm.ang)



boxplot(CTI ~ year, data = all.CTI)
boxplot(CTI ~ site, data = all.CTI)


```


