---
title: "CN effects on richness"
author: "Yiluan Song"
date: "2023-03-18"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, results = "hide")
knitr::opts_knit$set(root.dir = dirname(getwd()))
library(tidyverse)
library(flextable)
library(nlme)
library(broom.mixed)
library(flextable)
com_exp <- "data/community/all-experimental-data.rds"
```

```{r data}
df <- read_rds(com_exp) %>%
  filter(site == "jrgce", year >= 1999) %>%
  group_by(site, year, plot, treat) %>%
  summarise(richness = species %>% unique() %>% length()) %>%
  mutate(treat = case_when(
    treat == "____" ~ "_",
    treat == "__C_" ~ "C",
    treat == "___N" ~ "N",
    treat == "__CN" ~ "CN"
  )) %>%
  mutate(treat = factor(treat, levels = c("_", "C", "N", "CN"))) %>%
  drop_na(treat)
```

```{r boxplot-by-year, fig.width=8*1.618, fig.height=8}
#| fig.cap = "Figure 1. Grassland richness in ambient treatment (black), CO~2~ fertilization treatment (orange), N addition treatment (blue), and both CO~2~ fertilization and N addition treatment (green) over years in the Jasper Ridge Global Change Experiment."
ggplot(df) +
  geom_boxplot(
    aes(x = year, y = richness, col = treat, group = interaction(treat, year))
  ) +
  scale_color_manual(values = c("_" = "black", "C" = "dark orange", "N" = "dark blue", "CN" = "dark green")) +
  theme_classic()
```

Considering the large inter-annual variation in all plots, I subtracted all richness by the median richness in the ambient treatment of that year, in order to focus on the net effect of treatments. 

```{r adjust}
df_median <- df %>%
  filter(treat == "_") %>%
  group_by(year) %>%
  summarise(median = median(richness))

df_adj <- df %>%
  left_join(df_median, by = c("year")) %>%
  mutate(richness_adj = richness - median) %>%
  select(-median)
```

```{r boxplot-all, fig.width=6, fig.height=6}
#| fig.cap = "Figure 2. Grassland richness adjusted by the median ricness in ambient treatment (black) to show the net effect of CO~2~ fertilization treatment (orange), N addition treatment (blue), and both CO~2~ fertilization and N addition treatment (green) in all years (non-parametric two-sample Wilcoxon test, ns: *p* > 0.05, $*$: *p* ≤ 0.05, $**$: *p* ≤ 0.01, $***$: *p* ≤ 0.001))."
ggpubr::ggboxplot(
  data = df_adj,
  x = "treat",
  col = "treat",
  y = "richness_adj"
) +
  scale_color_manual(values = c("_" = "black", "C" = "dark orange", "N" = "dark blue", "CN" = "dark green")) +
  ggpubr::stat_compare_means(
    label = "p.signif",
    hide.ns = FALSE,
    comparisons = list(c("_", "C"), c("_", "N"), c("_", "CN")),
    size = 3
  ) +
  labs(
    x = "treatment",
    y = "richness (adjusted)"
  ) +
  theme_classic()
```

I fitted a linear mixed-effect model with random effect for year to estimate the effect of C, N, and CN treatments over all years.

```{r lme, results = 'markup'}
#| tab.cap = "Table 1. Model summary of linear mixed-effect model with a fixed effect of treatment and a random intercept for each year."
rich_lme <- lme(richness ~ treat, data = df, random = ~ 1 | year)
rich_lme %>%
  as_flextable()
```
