---
title: "Weighted SLA Change"
author: "Josie Lesage"
date: "7/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(stringr)
library(plotrix)
```

# Change in weighted SLA over time

```{r import data and get species ID list}
rel_all <- read.csv("Analysis/Traits/RelativeData.csv") %>% 
  select(-X) %>%
  mutate(species.name = str_squish(species.name)) %>%
  filter(relcov > 0) %>%
  mutate(species.name = recode(species.name,
                               "Festuca perennis" = "Lolium multiflorum",
                               "Lysimachia arvensis" = "Anagalis arvensis",
                               "Bromus madritensis ssp rubens" = "Bromus madritensis"))

species <- unique(rel_all$species.name)
species <- as.data.frame(species)

try_spp <- read.csv("Analysis/Traits/TryAccSpecies.csv") %>%
  rename(species.name = "AccSpeciesName")

try_IDs <- semi_join(try_spp, rel_all, by = "species.name")

# try_IDs <- unique(try_IDs$AccSpeciesID)
# try_IDs <- as.data.frame(try_IDs)
# try_IDs$try_IDs <- paste0(try_IDs$try_IDs, ",")
# cat(format_delim(try_IDs, delim = ""))

try_data <- read.csv("Analysis/Traits/TRY_Data.csv") %>%
  rename(species.name = AccSpeciesName) %>%
  filter(TraitID > 0) %>%
  select(-ObservationID, -ObsDataID)
try_data <- distinct(try_data) %>%
  group_by(species.name) %>%
  summarise(meanSLA = mean(StdValue))

rel_all_SLA <- left_join(rel_all, try_data, by = "species.name")
  
```


The goal is to use SLA data from the TRY database to (roughly) estimate the weighted SLA of these communities over time, further showing a potential change in species towards those that are adapted to hotter, drier climates. Basically, another line of evgidence to potentially show that these communities are drying over time. 

```{r weighted SLA}

rel_all_SLA_means <- rel_all_SLA %>%
  filter(meanSLA >= 0) %>%
  group_by(site, year, plot) %>%
  mutate(totcov = sum(cover),
         cov_inc = totcov/sumcov) %>%
  filter(cov_inc > 0.70)
  
rel_all_SLA_means <- rel_all_SLA_means %>%
  group_by(site, year, plot, species.name) %>%
  mutate(relcov = cover/totcov,
         weightedSLA = relcov*meanSLA) %>%
  group_by(site, year, plot) %>%
  summarise(mean_SLA = sum(weightedSLA)) %>%
    summarise(meanSLA = mean(mean_SLA),
              seSLA = std.error(mean_SLA))

ggplot(rel_all_SLA_means, aes(x = year, y = meanSLA, color = site)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymin = (meanSLA - seSLA), ymax = (meanSLA + seSLA))) +
  labs(title = "All sites - Specific Leaf Area",
       x = "Year",
       y = "Community-weighted SLA") +
  facet_wrap(~site, scales = "free", ncol = 4) +
  theme_bw() +
  theme(legend.position = "none") +
  geom_smooth(method = "lm")
  
```







