---
title: "CTI Analysis"
author: "Josie Lesage"
date: "1/23/2020"
output: html_document
---


```{r setup, include=FALSE}
## community analysis
library(codyn)
library(MASS)
library(lme4)
library(nlme)


## misc/both/other
library(oz)
library(plotrix)
library(tidyverse)
library(gridExtra)

theme_set(theme_bw())

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = '../') 

g_legend <- function(a.gplot){ 
    tmp <- ggplot_gtable(ggplot_build(a.gplot)) 
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box") 
    legend <- tmp$grobs[[leg]] 
    legend
}
```

```{r prism data import and prep, echo = FALSE}
weather <- read.csv("Analysis/ClimData/PRISM_data.csv") %>%
  select(-X)

wtryr_weather <- read.csv("Analysis/ClimData/PRISM_wtryr_data.csv") %>%
  select(-X)

```


```{r CTI import and prep, cache = TRUE}
ang_cti <- read.csv("Analysis/CTI Data/Angelo_CTI.csv")
car_cti <- read.csv("Analysis/CTI Data/Carrizo_CTI.csv") %>%
  rename(site = Site)
elk_cti <- read.csv("Analysis/CTI Data/Elkhorn_CTI.csv") %>%
  rename(site = Site)
jasp_cti <- read.csv("Analysis/CTI Data/Jasper_CTI.csv") %>%
  rename(site = Site)
McLAnn_cti <- read.csv("Analysis/CTI Data/McLAnn_CTI.csv")  %>%
  rename(site = Site)
mcLserp_cti <- read.csv("Analysis/CTI Data/McLSerp_CTI.csv") %>%
  rename(site = Site)
Swan_cti <- read.csv("Analysis/CTI Data/Swanton_CTI.csv")  %>%
  rename(site = Site)
UCSC_cti <- read.csv("Analysis/CTI Data/UCSC_CTI.csv")  %>%
  rename(site = Site)

all.CTI <- full_join(ang_cti, car_cti)
all.CTI <- full_join(all.CTI, elk_cti)
all.CTI <- full_join(all.CTI, jasp_cti)
all.CTI <- full_join(all.CTI, McLAnn_cti)
all.CTI <- full_join(all.CTI, mcLserp_cti)
all.CTI <- full_join(all.CTI, Swan_cti)
all.CTI <- full_join(all.CTI, UCSC_cti)

all.CTI <- all.CTI %>%
  dplyr::select(-X, -hotTI, -ColdTI) %>%
  mutate(site2 = factor(site, levels=c("Angelo", "Swanton", "UCSC", "Elkhorn", "Jasper", "McL Ann", "McL Serp", "Carrizo")))


all.CTI <- left_join(all.CTI, wtryr_weather, by = c("year", "site"))
```

```{r cti graph}
ggplot(all.CTI, aes(x=year, y=CTI, color = site2)) +
  geom_boxplot(aes(group = year)) +
      labs(title = "All sites - Community Temperature Index over time",
       x = "Year",
       y = "Community Temperature Index") +
  theme(legend.position = "bottom") +
  facet_wrap(~site2, nrow=2) 

ggplot(all.CTI, aes(x=year, y=CTI, color = site)) +
  geom_boxplot(aes(group = year)) +
      labs(title = "All sites - Community Temperature Index over time",
       x = "Year",
       y = "Community Temperature Index") +
  stat_smooth(method = "lm", se = F, size =  1)
  

ggplot(all.CTI, aes(x=year, y=CPI, color = site)) +
  geom_boxplot(aes(group = year)) +
      labs(title = "All sites - Community Precipitation Index over time",
       x = "Year",
       y = "Community Precipitation Index") +
  facet_wrap(~site, nrow=2) 
```


## Analysis of CTI

In our CTI model, we expect the following:  
* Response variables (one at a time)
+ CTI
+ CPI

* Fixed Effects
+ Time/Year
+ Climate factors?

* Random Effects
+ Site
+ Plot within site


```{r site-by-site CTI}
# angelo
ang.cti <- all.CTI %>% filter(site == "Angelo")
hist(ang.cti$CTI)
ang.cti.lm <- nlme::lme(CTI ~ year + tmin + precip,
                    data = ang.cti, method = "REML",
                    random =  ~ 1 | plot)
summary(ang.cti.lm)

# carrizo
car.cti <- all.CTI %>% filter(site == "Carrizo")
hist(car.cti$CTI)
car.cti.lm <- nlme::lme(CTI ~ year + tmin + precip,
                    data = car.cti, method = "REML",
                    random =  ~ 1 | plot)
summary(car.cti.lm)

# elkhorn
elk.cti <- all.CTI %>% filter(site == "Elkhorn")
hist(elk.cti$CTI)
elk.cti.lm <- nlme::lme(CTI ~ year + tmin + precip,
                    data = elk.cti, method = "REML",
                    random =  ~ 1 | plot)
summary(elk.cti.lm)

# jasper
jasp.cti <- all.CTI %>% filter(site == "Jasper")
hist(jasp.cti$CTI)
jasp.cti.lm <- nlme::lme(CTI ~ year + tmin + precip,
                    data = jasp.cti, method = "REML",
                    random =  ~ 1 | plot)
summary(jasp.cti.lm)

# mcL ann
mcLann.cti <- all.CTI %>% filter(site == "McL Ann")
hist(mcLann.cti$CTI)
mcLann.cti.lm <- nlme::lme(CTI ~ year + tmin + precip,
                    data = mcLann.cti, method = "REML",
                    random =  ~ 1 | plot)
summary(mcLann.cti.lm)

# mcL serp
mcLserp.cti <- all.CTI %>% filter(site == "McL Serp")
hist(mcLserp.cti$CTI)
mcLserp.cti.lm <- nlme::lme(CTI ~ year + tmin + precip,
                    data = mcLserp.cti, method = "REML",
                    random =  ~ 1 | plot)
summary(mcLserp.cti.lm)

# swanton
swan.cti <- all.CTI %>% filter(site == "Swanton")
hist(swan.cti$CTI)
swan.cti.lm <- nlme::lme(CTI ~ year + tmin + precip,
                    data = swan.cti, method = "REML",
                    random =  ~ 1 | plot)
summary(swan.cti.lm)


# ucsc
ucsc.cti <- all.CTI %>% filter(site == "UCSC")
hist(ucsc.cti$CTI)
ucsc.cti.lm <- nlme::lme(CTI ~ year + tmin + precip,
                    data = ucsc.cti, method = "REML",
                    random =  ~ 1 | plot)
summary(ucsc.cti.lm)




```

```{r all sites CTI}
hist(all.CTI$CTI)

## using lme; year only
cti.lm <- nlme::lme(CTI ~ year,
                    data = all.CTI, method = "REML",
                    random =  ~ 1 | site/plot)

summary(cti.lm)

grid.arrange(plot(cti.lm,type=c("p","smooth")),
             plot(cti.lm,sqrt(abs(resid(.)))~fitted(.),
                  type=c("p","smooth"),ylab=expression(sqrt(abs(resid)))),
                                       ## "sqrt(abs(resid(x)))"),
             plot(cti.lm,resid(.,type="pearson")~year,
                  type=c("p","smooth")),
             qqnorm(cti.lm,abline=c(0,1)))


## using lmer
cti.glm <- lmer(CTI ~ year + precip + tmin + (1|site/plot), data = all.CTI)
summary(cti.glm)
grid.arrange(plot(cti.glm,type=c("p","smooth")),
             plot(cti.glm,sqrt(abs(resid(.)))~fitted(.),
                  type=c("p","smooth"),ylab=expression(sqrt(abs(resid)))),
             plot(cti.glm,resid(.,type="pearson")~year,
                  type=c("p","smooth")),
             plot(cti.glm,resid(.,type="pearson")~precip,
                  type=c("p","smooth")),
             plot(cti.glm,resid(.,type="pearson")~tmin,
                  type=c("p","smooth")))


## using lme; 'full' model
cti.lm <- nlme::lme(CTI ~ year + tmin + precip,
                    data = all.CTI, method = "REML",
                    random =  ~ 1 | site/plot)
summary(cti.lm)
grid.arrange(plot(cti.lm,type=c("p","smooth")),
             plot(cti.lm,sqrt(abs(resid(.)))~fitted(.),
                  type=c("p","smooth"),ylab=expression(sqrt(abs(resid)))),
                                       ## "sqrt(abs(resid(x)))"),
             plot(cti.lm,resid(.,type="pearson")~year,
                  type=c("p","smooth")),
             qqnorm(cti.lm,abline=c(0,1)))



```

## Exit talk graphs
```{r exit talk graphs}
# calculating means and SEs
all.CTI.means <- all.CTI %>%
  group_by(site, year, site2) %>%
  summarise(mean.tmin = mean(tmin),
            mean.ppt = mean(precip),
            mean.CTI = mean(CTI),
            se.CTI = std.error(CTI),
            mean.CPI = mean(CPI),
            se.CPI = std.error(CPI))

# adding sig info
CTI.means.sig <- data.frame(site = c("Angelo", "Carrizo", "Elkhorn", "Jasper", "McL Ann", "McL Serp", "Swanton", "UCSC"),
                        sig = c("Yes", "Yes", "Yes", "Yes", "Yes", "No", "No", "Yes"))
all.CTI.means <- left_join(all.CTI.means, CTI.means.sig)

# 
ggplot(all.CTI.means, aes(x=year, y=mean.CTI, color = site2)) +
  geom_point() +
  geom_line(aes(linetype = sig)) +
  geom_errorbar(aes(x = year, ymin = mean.CTI-se.CTI, ymax = mean.CTI+se.CTI)) +
  labs(title = "Community Temperature Index",
       x = "Year",
       y = "Community Temperature Index (C)") +
  theme(legend.position = "left",
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.text.x = element_text(hjust = 1, vjust = 1, angle = 45),
        text = element_text(size = 14)) +
  scale_linetype_manual(values=c("dotted", "solid")) +
  facet_wrap(~site2, scales = "free", nrow = 2)

```



## Extra graphs?
```{r climate and CTI on same graph}
all.CTI.means <- all.CTI %>%
  group_by(site, year, site2) %>%
  summarise(mean.tmin = mean(tmin),
            mean.ppt = mean(precip),
            mean.CTI = mean(CTI),
            se.CTI = std.error(CTI),
            mean.CPI = mean(CPI),
            se.CPI = std.error(CPI))

(graph.clim.data <-ggplot(all.CTI.means) +
  geom_point(aes(x = year, y = mean.tmin*700, color = site), shape = 3) +
  geom_line(aes(x = year, y = mean.tmin*700, color = site)) +
  geom_bar(aes(x = year, y = mean.ppt, color = site, fill = site), 
           stat = "identity", position = "dodge") +
  geom_point(aes(x = year, y = mean.CTI*400, fill = site), shape = 5, color = "grey") +
  geom_line(aes(x = year, y = mean.CTI*400, color = site)) +
  geom_point(aes(x = year, y = mean.CPI*3, fill = site), shape = 7, color = "black") +
  geom_line(aes(x = year, y = mean.CPI*3, color = site)) +
  scale_y_continuous(sec.axis = sec_axis(~./700, name = "Temperature (C)")) +
  scale_x_continuous(limits = c(1980, 2020), breaks = seq(1980, 2020, 10), expand = c(0,0)) +
  labs(title = "Climate and CTI data for CA grasslands, 1982-2019",
       y = "Water Year Precipitation (mm)",
       x = "Year") +
  theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank(),
        axis.text.x = element_text(hjust = 0.5, vjust = 0.5, angle = 90)) +
  facet_wrap(~site, scales = "free", nrow = 2))


(graph.clim.data <-ggplot(all.CTI.means) +
  geom_point(aes(x = year, y = mean.CPI*700, color = site), shape = 5) +
  geom_line(aes(x = year, y = mean.CPI*700, color = site)) +
  geom_point(aes(x = year, y = mean.tmin*700, color = site), shape = 3) +
  geom_line(aes(x = year, y = mean.tmin*700, color = site)) +
  geom_bar(aes(x = year, y = mean.ppt, color = site, fill = site), 
           stat = "identity", position = "dodge") +
  scale_y_continuous(sec.axis = sec_axis(~./700, name = "Temperature (C)")) +
  scale_x_continuous(limits = c(1980, 2020), breaks = seq(1980, 2020, 10), expand = c(0,0)) +
  labs(title = "Climate and CTI data for CA grasslands, 1982-2019",
       y = "Water Year Precipitation (mm)",
       x = "Year") +
  theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank(),
        axis.text.x = element_text(hjust = 0.5, vjust = 0.5, angle = 90)) +
  facet_wrap(~site, scales = "free", nrow = 2))

(graph.clim.data <-ggplot(all.CTI.means) +
  geom_point(aes(x = year, y = mean.tmin*70, color = site), shape = 3) +
  geom_line(aes(x = year, y = mean.tmin*70, color = site)) +
  geom_bar(aes(x = year, y = mean.ppt, color = site, fill = site), 
           stat = "identity", position = "dodge", alpha = 0.5) +
  scale_y_continuous(sec.axis = sec_axis(~./70, name = "Temperature (C)")) +
  scale_x_continuous(limits = c(1980, 2020), breaks = seq(1980, 2020, 10), expand = c(0,0)) +
  labs(title = "Climate and CTI data for CA grasslands, 1982-2019",
       y = "Water Year Precipitation (mm)",
       x = "Year") +
  theme_bw() +
  theme(legend.position = "none",
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.text.x = element_text(hjust = 0.5, vjust = 0.5, angle = 90)) +
  facet_wrap(~site, nrow = 1))

graph.CTI <- ggplot(all.CTI.means) +
  geom_point(aes(x = year, y = mean.CTI, color = site), shape = 5) +
  geom_line(aes(x = year, y = mean.CTI, color = site)) +
  scale_x_continuous(limits = c(1980, 2020), breaks = seq(1980, 2020, 10), expand = c(0,0)) +
  labs(title = "Site-level Climate Data 1982-2019",
       y = "Community Temperature Index",
       x = "Year") +
  theme_bw() +
  theme(legend.position = "bottom",
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.text.x = element_text(hjust = 0.5, vjust = 0.5, angle = 90)) +
  facet_grid(~site)

graph.clim.leg <- g_legend(graph.CTI)

grid.arrange(graph.clim.data + theme(legend.position = "none"), 
             graph.CTI + theme(legend.position = "none"),
             graph.clim.leg,
             nrow = 3)



```
